### ISSUE TITLE
hardware参数写死了么？

### ISSUE THREAD

**Issue by dzhuang** [hanxi/xiaomusic#1]
不知道这个对不同的设备是否有影响.

**Comment by hanxi** [comment]
写了默认参数，其他的型号要传别的参数。

**Comment by hanxi** [comment]
也可以用环境变量了。

**Comment by firstuanl** [comment]
1代怎么办 MDZ-25-DA,

尝试填写：S12A/S12/L07A ?

**Comment by hanxi** [comment]
> 1代怎么办 MDZ-25-DA,
> 
> 尝试填写：S12A/S12/L07A ?

hardware 你看小爱屁股上有型号，输入进来，如果在屁股上找不到或者型号不对，可以用 micli mina 找到型号。
@firstuanl

**Comment by firstuanl** [comment]
> > 1 代怎么办 MDZ-25-DA,
> > 尝试填写：S12A/S12/L07A ?
> 
> hardware 你看小爱屁股上有型号，输入进来，如果在屁股上找不到或者型号不对，可以用 micli mina 找到型号。 @firstuanl

1 代 屁股上型号 是MDZ-25-DA, 看这篇，是用S12A/S12/L07A

[成了！将小爱音箱接入 ChatGPT - 小 z 博客]( https://blog.xiaoz.org/archives/20462 )

**Comment by hanxi** [comment]
@firstuanl 那你三个都试一下，不是3个一起填。

**Comment by firstuanl** [comment]
> @firstuanl 那你三个都试一下，不是3个一起填。

用python ./micli.py mina 拿到 
 'hardware': 'S12',
    'romVersion': '1.74.18',
    'capabilities': {
        'content_blacklist': 1,
        'lan_tv_control': 1,
        'night_mode_v2': 1,
        'school_timetable': 1,

现在就差解决登陆问题了。

**Comment by firstuanl** [comment]
如果能进docker改account。

系统只有python3.5不知怎弄3.10，用源码处理……
