### ISSUE TITLE
您好，麻烦问下，只能播放mp3格式的吗，能不能播放无损音乐？

### ISSUE THREAD

**Issue by tianxi2023** [hanxi/xiaomusic#10]

**Comment by hanxi** [comment]
我只过滤了mp3文件，不确定能不能播放flac，你可以用这个工具试试能不能播放flac格式的， 

https://github.com/yihong0618/MiService

如果可以的话，麻烦告知我下，我改改这个函数就行。

https://github.com/hanxi/xiaomusic/blob/main/xiaomusic/xiaomusic.py#L331

**Comment by hanxi** [comment]
@tianxi2023 最新代码已支持播放本地的 flac 格式音乐，欢迎测试体验。
