### ISSUE TITLE
在web控制台里面保存配置后生成的setting.json里面music_path_depth对应的是字符串，后面用这个配置启动的时候，会出现字符串和数字比较大小的错误

### ISSUE THREAD

**Issue by scanftu** [hanxi/xiaomusic#110]

**Comment by hanxi** [comment]
方便发下日志看看吗？我这里虽然 setting.json 是字符串，但是启动后生成 config 对象里的数据会转为 int

**Comment by scanftu** [comment]
![image](https://github.com/hanxi/xiaomusic/assets/30646461/130bb508-7c2c-4d1b-8e6d-0c1825ca8b6b)

**Comment by scanftu** [comment]
> 方便发下日志看看吗？我这里虽然 setting.json 是字符串，但是启动后生成 config 对象里的数据会转为 int
![image](https://github.com/hanxi/xiaomusic/assets/30646461/20e572c1-a8f8-4871-8832-47365f284f38)

**Comment by scanftu** [comment]
把setting.json 里面"10"改成10启动就不会失败

**Comment by hanxi** [comment]
看来windows下有问题

**Comment by hanxi** [comment]
懂了，是config.json和setting.json不一样的问题，下个版本修复。
