### ISSUE TITLE
L05C没有提示音

### ISSUE THREAD

**Issue by smallcoderhujin** [hanxi/xiaomusic#112]
如题，播放歌曲都是正常的，但是任何提示音都没有

比如web页面点击下一首，会短暂空白一段时间（感觉在讲话，但是没声音），大概5s左右，然后继续播放

感谢作者的辛勤付出，非常好用

**Comment by hanxi** [comment]
那点击 全部循环 单曲循环 这些有提示音吗？

**Comment by smallcoderhujin** [comment]
都没有提示音，点击后短暂空白，然后继续播放

**Comment by hanxi** [comment]
感谢反馈，应该是另外一个让小爱说话的接口有问题。

**Comment by wyx-dev** [comment]
老哥，这个测试了下，L05C text_to_speech
            await self.xiaomusic.mina_service.text_to_speech(self.device_id, value)  这个接口调用完成了，但是L05C 设备没有说话。这个有办法解决吗？老哥，期待回复，多谢

**Comment by hanxi** [comment]
有办法，就是比较麻烦，可以准备好提示音的mp3文件，用play_music_url那个接口。

**Comment by flymin** [comment]
我这边测试 L05C 使用 MiIOService，可以用 tts 发声，之后推下 pr

**Comment by hanxi** [comment]
0.3.38 版本可用。
