### ISSUE TITLE
建议播放失败自动切下首歌

### ISSUE THREAD

**Issue by Zding89** [hanxi/xiaomusic#116]
发现在播放过程中有时候一段时间没声音，看调试文件是播放失败，然后等待722秒

**Comment by hanxi** [comment]
![Image_1721061021752](https://github.com/user-attachments/assets/6f86e478-194e-4738-ad05-e4e0f51920ab)
记录一下报错日志

**Comment by hanxi** [comment]
0.3.5 版本修复
