### ISSUE TITLE
歌曲和播放列表都存在播放不完整的情况

### ISSUE THREAD

**Issue by huo987** [hanxi/xiaomusic#117]
播放歌曲有时播放开头一部分后 切回上一首歌或者其他歌曲的现象
播放列表有时歌单只播了几首，就播其他歌曲

**Comment by hanxi** [comment]
mp3 文件播放时长获取错误问题会在 0.3.0 版本修复。见 #114

**Comment by hanxi** [comment]
v0.3.22版本应该已经修复。
