### ISSUE TITLE
音乐目录支持软链接

### ISSUE THREAD

**Issue by SherwinWg** [hanxi/xiaomusic#119]
1，希望支持music下的软连接目录
2，希望触屏版支持歌曲名，歌词
3，希望支持暂停播放，下一首，上一首，速度等操作

**Comment by hanxi** [comment]
1可以做到，2做不到，3只支持停止，可以考虑加入上一首。

**Comment by hanxi** [comment]
功能分开提

**Comment by SherwinWg** [comment]
Music目录下放了软连接（执行别的地方音乐目录），在播放列表里面还是显示不出来。

**Comment by hanxi** [comment]
具体说说你的配置和路径是怎么设置的？看看是不是软连接的问题。
