### ISSUE TITLE
希望支持Navidrome

### ISSUE THREAD

**Issue by hotlcc** [hanxi/xiaomusic#121]
https://github.com/navidrome/navidrome

**Comment by hanxi** [comment]
那个不熟，需要有人写插件。

**Comment by hotlcc** [comment]
> 那个我不熟，需要有人写插件。

具体我也没研究过，应该是有api的。我现在基本上是Navidrome做音乐推流服务，手机端用音流APP播放，很好用的，如果xiaomusic能支持从Navidrome搜索音乐并播放就好了。
