### ISSUE TITLE
pip安装方式下，static目录找不到报错

### ISSUE THREAD

**Issue by tmsdy** [hanxi/xiaomusic#122]
我的启动方式是:xiaomusic --config /home/pi/Desktop/xiaomusic/config.json

配置如下：
![3d00500c095c62a4371de22bbf0a107](https://github.com/user-attachments/assets/c569c6ab-3790-4c89-9162-bb9e5e03ec60)

报错如下：
![c55e04aeee4c3884864e911394f019b](https://github.com/user-attachments/assets/3fb23279-b676-4645-96e8-6726fa59d8d6)

解决方法是 把static目录复制到 /home/pi/Desktop/xiaomusic/xiaomusic/static

**Comment by hanxi** [comment]
0.3.2 版本修复。

**Comment by longnk** [comment]
刚升级到0.3.4也遇到这问题了
