### ISSUE TITLE
0.3.1 音乐停止和自己播放的问题

### ISSUE THREAD

**Issue by huo987** [hanxi/xiaomusic#123]
0.3.1版本，设置了多设备，小爱音箱播放音乐时，如果音箱播报系统通知，音乐会停止播放。
另一个问题，一台没有设置播放音乐的设备会自己播放音乐，语音指令让其关机后，一会儿后又开始自动播放音乐，查看控制页面发现后台显示在播放中
[xiaomusic.txt](https://github.com/user-attachments/files/16233975/xiaomusic.txt)

**Comment by hanxi** [comment]
分组里的冒号和逗号需要是英文的:

`594396612:浴室,603867344:厨房,604107063:卧室`

**Comment by hanxi** [comment]
每个设备为不同组的情况是可以不设置组名的。音乐名是在小爱音箱app里设置的。

**Comment by hanxi** [comment]
报系统通知会打断音乐，目前无法检测到，所以不会自动播放，下一首歌曲定时器到了会开始播放下一首。
