### ISSUE TITLE
0.3.1升级后播放出现卡顿

### ISSUE THREAD

**Issue by joker379** [hanxi/xiaomusic#124]
0.3.1升级后播放出现卡顿，问题持续有5-10分钟，之后恢复正常，默认参数，未开启下载功能，复选设备S12和LX01

**Comment by hanxi** [comment]
更新后试试看有没有修复。

**Comment by hanxi** [comment]
v0.3.22版本应该已经修复。

**Comment by lzqoscar** [comment]
0.3.37 设备L05C又出现卡顿了 之前在0.3.36的时候貌似不卡。使用自带的测试链接播放不卡，使用语音或者web输入周杰伦七里香这样方式都会卡顿。

**Comment by lzqoscar** [comment]
> > 0.3.37 设备L05C又出现卡顿了 之前在0.3.36的时候貌似不卡。使用自带的测试链接播放不卡，使用语音或者web输入周杰伦七里香这样方式都会卡顿。
> 
> 已知 0.3.39 版本会修复。

刚发现和版本无关，重启音响之后好了，L05C真离谱啊，设置5-3也会说话了。感谢大佬！不过有个问题我的小爱总是先按正常流程响应，之后才会被xiaomusic的指令覆盖，这个正常吗
