### ISSUE TITLE
0.3.1 本地英文歌曲匹配不到

### ISSUE THREAD

**Issue by tmsdy** [hanxi/xiaomusic#125]
![D8129567-EDC9-4A3B-8CA8-CD4A6646E3BC](https://github.com/user-attachments/assets/7f508b6e-d167-4f48-8af4-d9cae9d7fe22)
![FBF25631-92AB-47D0-A90C-D9915D41B743](https://github.com/user-attachments/assets/b084f789-5f71-45f7-91c2-7e1fd0609ee1)
语音控制，播放本地的音乐，实际上本地的名字是What about us  语音识别出来的都是大写，导致程序找不到匹配的文件。

**Comment by hanxi** [comment]
0.3.4修复
