### ISSUE TITLE
0.3.11版两台L09A总是同时播放

### ISSUE THREAD

**Issue by crek2002** [hanxi/xiaomusic#132]
我有两台L09A,在设置里这两个设备都勾选了，设备未分组，但无论是通过语音“播放本地歌曲”唤醒任意一台L09A或者是在web界面选择任意一台L09A点播放，两台L09A总是同时播放，可这种情况下我并不想另一台也同时播放，是我设置的问题吗？

**Comment by hanxi** [comment]
看看你的setting.json文件，把账号密码删了。

**Comment by hanxi** [comment]
@crek2002 请问问题还存在吗？
