### ISSUE TITLE
没有设备列表

### ISSUE THREAD

**Issue by majianming21** [hanxi/xiaomusic#137]
背景：
版本 0.3.24 截止当前最新
按照要求填入mi_did,password,account之后，启动没有错误
硬件LX05
问题：
在列表框无法选择任何设备
![图片](https://github.com/user-attachments/assets/47337eb2-0e36-4dfe-95f7-3d239fe9c978)
getsetting 接口返回的device 为空是正常的吗
![图片](https://github.com/user-attachments/assets/6ac83bf6-685c-43d0-b522-d71d94fff8e7)

**Comment by hanxi** [comment]
去设置页面设置账号密码试试？
