### ISSUE TITLE
BAK文件

### ISSUE THREAD

**Issue by bj803** [hanxi/xiaomusic#139]
在音乐文件夹里生成了好多BAK文件（播放
![IMG_5771](https://github.com/user-attachments/assets/c3e7de0f-26e7-43c6-81ac-3a44677563d4)
后就生成一个BAK文件）

**Comment by hanxi** [comment]
https://github.com/hanxi/xiaomusic/issues/120
是这个功能的结果，设置页面有个开关，关了之后就不会了。
