### ISSUE TITLE
全部循环和随机播放都无法自动切歌

### ISSUE THREAD

**Issue by Yuuki-Rin** [hanxi/xiaomusic#140]
全部循环和随机播放下一首歌播放完无法自动切换下一首歌
会卡一会然后重新播放刚刚播放过的那首
只能手动点下一首或者喊小爱 下一首
音响L05C 
版本[0.3.24](https://github.com/hanxi/xiaomusic/blob/main/CHANGELOG.md))
第一次进行配置使用不知道是不是哪里配置的不对

**Comment by hanxi** [comment]
可能是获取不到歌曲时长，看看你的日志？

**Comment by Yuuki-Rin** [comment]
> 可能是获取不到歌曲时长，看看你的日志？
[_xiaomusic_logs.txt](https://github.com/user-attachments/files/16518534/_xiaomusic_logs.txt)

**Comment by hanxi** [comment]
![Screenshot_2024-08-07-15-40-48-369_com android chrome](https://github.com/user-attachments/assets/8e4905dd-536e-4199-bab8-a65c0323c7f3)
方便发下这首歌曲吗？确实获取歌曲时长失败。

**Comment by Yuuki-Rin** [comment]
> ![Screenshot_2024-08-07-15-40-48-369_com android chrome](https://private-user-images.githubusercontent.com/1185757/355721212-8e4905dd-536e-4199-bab8-a65c0323c7f3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTcxMTgsIm5iZiI6MTcyMzAxNjgxOCwicGF0aCI6Ii8xMTg1NzU3LzM1NTcyMTIxMi04ZTQ5MDVkZC01MzZlLTQxOTktYmFiOC1hNjVjMDMyM2M3ZjMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMDc0NjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY5M2IzNWMzNWNlOTVkMWEwZjY4NTUzZmViNTk3YzBkMGIyMWJiZDdlOGMxOWFmZDFmMGM4NTJkMzc4Zjg0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YQUymMjafEHEhIwwdVJI5pOmSQZrPtnfSug06EzU0c0) 方便发下这首歌曲吗？确实获取歌曲时长失败。

应该不是单首歌曲的问题
只要不手动下一首都这样

**Comment by Yuuki-Rin** [comment]
> ![Screenshot_2024-08-07-15-40-48-369_com android chrome](https://private-user-images.githubusercontent.com/1185757/355721212-8e4905dd-536e-4199-bab8-a65c0323c7f3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTk3NzIsIm5iZiI6MTcyMzAxOTQ3MiwicGF0aCI6Ii8xMTg1NzU3LzM1NTcyMTIxMi04ZTQ5MDVkZC01MzZlLTQxOTktYmFiOC1hNjVjMDMyM2M3ZjMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMDgzMTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTc4YThkMzJjNTEwZWI0MGJmOGRjOWZlMTgwZmQ3NTM4ZTQ1ZjhiNTA3ZjU5NmExNzc4YWU0ODNkZjc1YjJjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8SoQwetc5uG2RTozp4_OkuCop3daxbMFxPSqcpoP7oc) 方便发下这首歌曲吗？确实获取歌曲时长失败。

大佬我找到问题了是这个格式的锅
全转成mp3他就可以正常识别时间并触发定时器
