### ISSUE TITLE
能否添加多账户支持

### ISSUE THREAD

**Issue by liuqq58** [hanxi/xiaomusic#141]
需求背景
我和我哥是各有各自己音箱，但是因为住不远，是同个局域网内，多个账户可以很好的实现不同音箱的单独调用。现在只能添加一个账户，等于如果要用，最好是在搭建一个docker容器，但是在同一个局域网，在搭建一个也不知道会不会冲突。
搭建两个会冲突吗？？？
需求内容
首先 账户添加页面，可以添加两个账户或以上，添加页面可以添加备注，因为音箱型号是一样的，小爱音箱操控面板，可以切换设置，而不是都显示，设置的时候需要选择设置哪一台， 方便设置区分

不知道能否实现，太麻烦就算了，大概是冷门需求。

**Comment by hanxi** [comment]
搭两个容器吧，用不同端口即可。
