### ISSUE TITLE
群晖docker升级镜像进不了UI

### ISSUE THREAD

**Issue by bj803** [hanxi/xiaomusic#142]
群晖docker升 0.3.25 镜像进不网页UI (与3周的一个版本一样)
![screenshot-1723885729491](https://github.com/user-attachments/assets/ada2dd30-696a-45fb-94d7-4c2910da21f8)

**Comment by hanxi** [comment]
删除setting.json文件再试试

**Comment by bj803** [comment]
删除setting.json可以了
谢谢
