### ISSUE TITLE
L05C是否可以强制转码播放？

### ISSUE THREAD

**Issue by Hi-Jiajun** [hanxi/xiaomusic#143]
音乐库内都是AppleMusic中下载的，m4a后缀的无损音乐和杜比全景声，以及某些flac后缀的无损音乐，用httpRandomMusic可以转码播放，本项目也可以控制音量大小有提示音，但无法播放出声音，估计是无法直接播放，不知道可不可以强制其转码后播放？

**Comment by hanxi** [comment]
可以加个选项搞一搞，你会搞的话可以提个pr，我最近没啥时间。可以参考 https://github.com/hanxi/xiaomusic/pull/129/files 在获取歌曲时判断是不是mp3，不是就用ffmpeg转一下。

**Comment by Hi-Jiajun** [comment]
已经提了pr了，第一次搞，有所不足，烦请作者老哥见谅！

**Comment by hanxi** [comment]
感谢，已经合并。
