### ISSUE TITLE
感觉可以开个针对小爱音箱的org awesome-xiaoai

### ISSUE THREAD

**Issue by zzz6519003** [hanxi/xiaomusic#147]

**Comment by hanxi** [comment]
我没精力维护哦，你有时间的话可以搞个。我知道的就这些

1. https://github.com/yihong0618/xiaogpt
2. https://github.com/yihong0618/MiService
3. https://github.com/idootop/mi-gpt
4. https://github.com/longbai/xiaobot
5. https://github.com/al-one/hass-xiaomi-miot
6. https://github.com/shaonianzhentan/ha_cloud_music

**Comment by zzz6519003** [comment]
https://github.com/zzz6519003/awesome-xiaoai
