### ISSUE TITLE
spotify API接口

### ISSUE THREAD

**Issue by River-261** [hanxi/xiaomusic#150]
不知道能否增加spotify或是其他音源的api接口，这样以后不需要下载音乐也能轻松线上听歌，谢谢大神

参考网页
https://developer.spotify.com/documentation/web-api

**Comment by hanxi** [comment]
可以写外部工具导出符合xiaomusic歌单格式的json文件来实现，不建议直接集成到xiaomusic内部。

**Comment by hanxi** [comment]
歌单格式见 #78

**Comment by River-261** [comment]
可能我表达的不够好，并非用歌单的方式，而是用语音或面板请小爱播放某歌曲然后改透过spotify api 搜寻歌曲并播放音乐，谢谢

**Comment by hanxi** [comment]
理解你的意思了。目前只支持 yt-dlp 下载歌曲，如果需要支持其他的，需要实现跟 yt-dlp 类似的接口才方便引入。我看 yt-dlp 是支持 spotify 的，不确定能否支持搜索下载。
