### ISSUE TITLE
无法播放ape以及flac格式的歌曲

### ISSUE THREAD

**Issue by Lanny2020** [hanxi/xiaomusic#153]
在music目录中放置有：mp3，ape，flac格式的歌曲，但只有mp3格式的能播放，其他格式的歌曲UI会显示“播放中”，但音箱没声音。

音箱型号：小爱音箱Pro（LX06）

![Snipaste_2024-09-04_01-03-12](https://github.com/user-attachments/assets/3b6e185c-0195-4ec0-a746-3552970a9e39)

**Comment by hanxi** [comment]
应该是音箱型号不支持这些类型，有个【转换为MP3】再播放的选项，你可以试试。

**Comment by Lanny2020** [comment]
谢谢回复。
1、【触屏版兼容模式】”该选项打开后，可以播放FLAC格式，但APE还是不行。
2、【转换为MP3】打开后，会将其他所有格式都自动转成mp3播放。
3、我试了 LX06 和 L16A 都存在上述问题。

**Comment by lazybabyz** [comment]
> LX06

LX06最优品质可以用哪一个? 320K? 感谢~

**Comment by hanxi** [comment]
不清楚，我只听个响。

**Comment by zazhi4** [comment]
【转换为MP3】打开后，是下载文件自动转为了MP3，可以直接播放，但是原文件就没有了；还是，不管什么格式，先下载了，播放时以MP3格式播放？如果原文件没有的话，建议用320k（也就是高码率，尽量高的质量）来转换为MP3。

**Comment by hanxi** [comment]
> 【转换为MP3】打开后，是下载文件自动转为了MP3，可以直接播放，但是原文件就没有了；还是，不管什么格式，先下载了，播放时以MP3格式播放？如果原文件没有的话，建议用320k（也就是高码率，尽量高的质量）来转换为MP3。

原文件还在的，转换后的文件在tmp目录。

**Comment by zazhi4** [comment]
我用lx06，实测，wav能放。我就将自己保存的ape，flac，都转为wav了。

**Comment by IsMars6** [comment]
遇到无法播放的音乐格式目前不会自动跳过，会提示播放服务遇到问题。
另外触屏音响会出现歌曲信息不一致问题

**Comment by Rogue9665** [comment]
> > 【转换为MP3】打开后，是下载文件自动转为了MP3，可以直接播放，但是原文件就没有了；还是，不管什么格式，先下载了，播放时以MP3格式播放？如果原文件没有的话，建议用320k（也就是高码率，尽量高的质量）来转换为MP3。
> 
> 原文件还在的，转换后的文件在tmp目录。

需要把tmp目录映射出来定期清理吗？

**Comment by ideajoker** [comment]
我测了一下 家里的小爱音箱Pro（LX06）都可以播放，同一个目录里面的FLAC、MP3、WAV 都可以。
之前版本是0.3.2时候好像都可以，昨天晚上升级到0.4.4也一样正常播放，也有声音
<img width="1447" height="830" alt="Image" src="https://github.com/user-attachments/assets/821c84fe-ee2f-45d2-8782-b0d1398ac544" />

**Comment by qinqoushui** [comment]
挑FLAC，有的可以，有的不可以，不知道原因
