### ISSUE TITLE
希望能像落雪音乐一样导入音源,并有播放歌单功能。

### ISSUE THREAD

**Issue by sdfsdfw2** [hanxi/xiaomusic#155]
希望能像落雪音乐一样导入音源,并有播放歌单功能。再加个UI就完美了，

**Comment by hanxi** [comment]
见 #71 。目前不支持哈，有兴趣可以写插件转换歌单格式。

**Comment by hanxi** [comment]
目前是支持导入歌单，但是需要有人分享歌单才行。需要有歌单转换工具。

**Comment by hanxi** [comment]
lx 歌单插件参考 https://github.com/dissipator/xiaomusic/blob/dev/plugins/getmy_playlist.py
