### ISSUE TITLE
播放目录如何修改为其它硬盘的目录，默认目录空间太小

### ISSUE THREAD

**Issue by lishx8888** [hanxi/xiaomusic#157]
rtrt

**Comment by hanxi** [comment]
```
docker run -p 8090:8090 \
    -v /xiaomusic/music:/app/music \
    -v /xiaomusic/conf:/app/conf \
    hanxi/xiaomusic
```

把命令中的 `/xiaomusic/music` 改为其他目录即可。

**Comment by lishx8888** [comment]
> ```
> docker run -p 8090:8090 \
>     -v /xiaomusic/music:/app/music \
>     -v /xiaomusic/conf:/app/conf \
>     hanxi/xiaomusic
> ```
> 
> 把命令中的 `/xiaomusic/music` 改为其他目录即可。

二次更改就找不到歌了

**Comment by hanxi** [comment]
docker 目录映射出问题了吧，重启试试。
