### ISSUE TITLE
播放列表每次都从第一个开始播放

### ISSUE THREAD

**Issue by dludream** [hanxi/xiaomusic#158]
播放列表每次都从第一个开始播放，无法控制播放 播放列表的第几个文件。

希望可以控制播放 播放列表的第几个文件，文件名可能比较长，听书的时候，例如可以说，“小爱同学，播放列表第3个 水浒传”  来播放水浒传列表的第3个文件。

**Comment by hanxi** [comment]
播放列表没有从上次关机时候的开始播放吗？播放列表第几个我看看好不好实现。

**Comment by dludream** [comment]
> 播放列表没有从上次关机时候的开始播放吗？播放列表第几个我看看好不好实现。

没有，并且播放的过程中，如果调整了音量等对小爱进行了控制，会从头开始播放播放列表，总之就是反反复复播放第一集，放不到后面去。
所以才建议可以控制播放'播放列表'的某个文件。

**Comment by hanxi** [comment]
下个版本可以用使用你设计的这个口令，非首次安装时，需要重新设置【允许唤醒的命令:】为 `play,set_random_play,playlocal,play_music_list,play_music_list_index,stop_after_minute,stop`

**Comment by hanxi** [comment]
每次都从第一个开始播放的bug应该已经修复了。

**Comment by dludream** [comment]
辛苦啦

**Comment by shishanfeng** [comment]
0.3.37新版本添加了play,set_random_play,playlocal,play_music_list,play_music_list_index,stop_after_minute,stop，[新增口令【播放列表第几个+列表名】来播放列表里的第几个，好像还不好用，可不可以增加播放列表第几个的口令，分两步，第一步播放列表，第二步播放第几个，或者支持下几首，是不是实现简单一些

**Comment by hanxi** [comment]
> 0.3.37新版本添加了play,set_random_play,playlocal,play_music_list,play_music_list_index,stop_after_minute,stop，[新增口令【播放列表第几个+列表名】来播放列表里的第几个，好像还不好用，可不可以增加播放列表第几个的口令，分两步，第一步播放列表，第二步播放第几个，或者支持下几首，是不是实现简单一些

播放列表第几个+列表名 这个还没发布版本哦。

**Comment by shishanfeng** [comment]
我还以为已经更新了😂，辛苦哈

**Comment by zzy19868** [comment]
> > 0.3.37新版本添加了play,set_random_play,playlocal,play_music_list,play_music_list_index,stop_after_minute,stop，[新增口令【播放列表第几个+列表名】来播放列表里的第几个，好像还不好用，可不可以增加播放列表第几个的口令，分两步，第一步播放列表，第二步播放第几个，或者支持下几首，是不是实现简单一些
> 
> 播放列表第几个+列表名 这个还没发布版本哦。等 0.3.38 版本。分2个命令比较麻烦的，得叫2次小爱同学。
大大，播放列表第几个+列表名喊不动啊，比如播放列表第10个猴子警长，不得行
