### ISSUE TITLE
新增的网页播放不能停止，如果重复按会重复播放，结果就是你按多少次播放，就会根据你按的次数和间隔时间播放多次音乐

### ISSUE THREAD

**Issue by drkulaasdf** [hanxi/xiaomusic#166]
新增的网页播放不能暂停，如果重复按会重复播放，结果就是你按多少次播放，就会根据你按的次数和间隔时间播放多次音乐

**Comment by hanxi** [comment]
有待优化，目前只是试听，可以改成单曲循环或者只播放一次，然后重复点击把旧的关掉。

**Comment by hanxi** [comment]
下个版本修复。

**Comment by 52fisher** [comment]
```
        if (window.currentMusic) {
          window.currentMusic.pause();
          window.currentMusic.currentTime = 0;
        }
        window.currentMusic = new Audio(data.url);
        window.currentMusic.play();
```

@hanxi 用new Audio()不如用h5的新标签 
`<audio src='data.url' controls autoplay></audio>`
每次更换歌曲只需要$('audio').attr('src',data.url)就行了
![图片](https://github.com/user-attachments/assets/6d87b0cf-75c8-478b-a2f9-4838819605fe)


另外，这个搜索app.js line248 是不是应该debounce一下，多搜索几个字符会造成不停的请求，我调试接口的时候有几次直接无法应了
![图片](https://github.com/user-attachments/assets/bbb9c6a2-5209-467e-bc53-880d26a34fef)
