### ISSUE TITLE
【探讨】关于播放接口的类型设置

### ISSUE THREAD

**Issue by grayana** [hanxi/xiaomusic#170]
经过测试，L06A和LX04，在启用触屏版兼容模式（即使用play_by_music_url）并设置type=1时，音乐播放不会因为与小爱对话而终止。
![image](https://github.com/user-attachments/assets/cd73bc87-beb6-464b-9c4e-8a2a9b14b409)
是否考虑设置type为1，并在使用play_by_music_url时不执行【继续播放歌曲】这一指令。这样音乐就不会从头重新播放。
![image](https://github.com/user-attachments/assets/6fbaaa36-bdb1-42f5-ae91-d126723ef00e)
当然其它设备暂时没法测试。可能还需要更多人来测试下。

**Comment by hanxi** [comment]
可以做成可选配置，比如叫【继续播放不重头开始】，默认不开启就行，这样就不会影响旧用户。

**Comment by grayana** [comment]
可以👍，我下午看下能不能搞定，如果搞好提个pr
