### ISSUE TITLE
music 文件夹下，可否支持软链接，把现有的别的地方的音乐链接过来？

### ISSUE THREAD

**Issue by guoxiangke** [hanxi/xiaomusic#175]
<img width="154" alt="image" src="https://github.com/user-attachments/assets/60055a28-dfba-458a-9b45-1906df9fbb8d">

还有，我有很多音乐并不是以歌名命名的，比如每个文件夹下都是01.mp3 02.mp3 。。。
有何更好的解决方案，谢谢。

**Comment by hanxi** [comment]
软连接是支持的，文件名重复的问题没啥好办法。

**Comment by guoxiangke** [comment]
播放列表设计可能需要重构成 列表名.index.歌名 方式

**Comment by hanxi** [comment]
> 播放列表设计可能需要重构成 列表名.index.歌名 方式

不是很理解为何这样设计，歌名不能重复是为了语音播放歌曲方便。

**Comment by Q191** [comment]
支持软链接?我链接了一个目录和文件，都识别不了，把文件放到目录下就行

**Comment by Q191** [comment]
> 支持软链接?我链接了一个目录和文件，都识别不了，把文件放到目录下就行

只能切换目录了

**Comment by hanxi** [comment]
软连接对应的那个实际文件你都得挂载进docker里才能识别的。
