### ISSUE TITLE
歌曲目录能否支持多级文件夹

### ISSUE THREAD

**Issue by loveu5522** [hanxi/xiaomusic#18]
因为歌曲比较多，测试只能识别映射的根目录歌曲，能否支持识别目录下子文件夹下的歌曲

**Comment by hanxi** [comment]
你这个需求比较简单，等我有空加下。你如果会python的话，也可以提个pr给我合并一下。改random_music和local_exist两个函数应该就可以实现。

**Comment by loveu5522** [comment]
大佬我不会python，您有空给加一下吧

**Comment by zhanggaolei001** [comment]
臣附议!

**Comment by hanxi** [comment]
等这个周末安排一下

**Comment by hanxi** [comment]
@loveu5522 @zhanggaolei001 已经支持读取子目录，有空可以测测。

**Comment by zhanggaolei001** [comment]
> @loveu5522 @zhanggaolei001 已经支持读取子目录，有空可以测测。

我更新了docker的，好像没效果啊

**Comment by wangweitung** [comment]
> @loveu5522 @zhanggaolei001 已经支持读取子目录，有空可以测测。

thanks！
