### ISSUE TITLE
小爱音箱语音功能增强

### ISSUE THREAD

**Issue by River-261** [hanxi/xiaomusic#183]
感谢大神网页版的功能一直不断强化
想请问一下大神是否有考虑加强语音操控方面的控制，比方说下一首，上一首，删除歌曲(歌曲播放一半时，遇到不喜欢的或下错版本可以删除)，或是随机播放，单曲循环，这些网页的功能，能否在网页上自定义口令的方式，网页操作虽然方便，但感觉如果能用语音的控制，可以更能展现小爱音箱强项

**Comment by hanxi** [comment]
已经支持的口令有很多了哦。删除歌曲是危险操作，不太想加入语音。
```
        "分钟后关机",
        "播放歌曲",
        "下一首",
        "上一首",
        "单曲循环",
        "全部循环",
        "随机播放",
        "关机",
        "刷新列表",
        "播放列表",
        "加入收藏",
        "取消收藏",
```
部分口令的提示词可以在后台修改。

**Comment by River-261** [comment]
好的，感謝
