### ISSUE TITLE
文件名包括文件夹路径；播放列表排序问题

### ISSUE THREAD

**Issue by flymin** [hanxi/xiaomusic#186]
1. 文件名包括文件夹路径
    我的音乐库整理格式为：歌手名/专辑名/单曲名.ext。这种情况下只从文件名索引歌手名字是找不到的，如果改成包括文件夹路径则可以支持
2. 播放列表排序
    个人感觉”所有音乐“，“全部”，“电台”等放在列表最上面会方便网页查找

以上两点已实现，如果可以采纳的话我可以提 pr

**Comment by hanxi** [comment]
第1点对现有的语音播放歌曲有影响不？没影响的话可以提pr。第2点直接提pr吧（应该只是改前端代码吧，后端返回的是个无需的dict）。

**Comment by 52fisher** [comment]
> 第1点对现有的语音播放歌曲有影响不？没影响的话可以提pr。第2点直接提pr吧（应该只是改前端代码吧，后端返回的是个无需的dict）。
第一点怎么可能没影响，开什么玩笑。稳定的功能别乱改代码啊。
不要随便改动已经稳定的核心代码，模糊匹配的数值改动前后不平衡，会严重影响功能。
这种改动最好在设置中心加开关。
第二点用不上，Object本身是无序的，前端获取分类靠的是Object.keys(obj)，渲染和数据是区分的

**Comment by flymin** [comment]
关于排序：

前端实现按类别排序需要假设已知后端会返回哪些类型的列表名称，API 的约定也要变的更严格。意味着如果未来有更多类别加入，前端都需要一一做适配。

相比之下，目前前端没有重排序的功能，将 API 都改为有序表影响最小。后期如果前端考虑支持重排序，再实现即可。

另外，我不懂js，如果有能兼容的排序写法，保持接口无序和改到前端重排我没意见。

**Comment by flymin** [comment]
歪个楼，第三方前端不建议加入源代码中，参考qbittorrent 的实现方式，默认只包括一个全功能界面，设置里指定路径就可以调用第三方前端。

这样做的好处：
1. 第三方前端更新不需要发布新版本，开发中的前端可以逐渐支持 API，不需要一次性完成适配
2. 减小发布体积
3. 用户可以切换任意前端实现，更容易拓展
4. 本仓库只维护核心代码及 API
5. landing page 不需要选择 UI，使用更流畅

**Comment by 52fisher** [comment]
1.本身设置里面就可以指定主题路径
2.前端是可以逐渐支持API，但是你后端不要随便的乱改动，不要随便的乱改动接口!!!! 新旧接口不兼容，前端怎么给你做兼容
3.无论你后端返回是字典序，还是有序表，后端的返回数据类型是object，传到前端取出来的字段仍然是无序的，要么就改数据结构。现在返回的数据到前端都是要重新排序的

**Comment by flymin** [comment]
> 3.无论你后端返回是字典序，还是有序表，后端的返回数据类型是object，传到前端取出来的字段仍然是无序的，要么就改数据结构。现在返回的数据到前端都是要重新排序的

ok我理解了，我说的列表类型是指
1. 关键词列表（”所有“，”全部歌曲“等）
2. 网络歌单
3. 文件夹歌单

检索列表类型的接口应该没给到前端，所以前端没法根据类型排序，尤其是“关键词列表”应该保证在前/在后。我理解有几种改法：
1. 改成有序的接口
2. 额外提供一个列表顺序 API
3. 提供获取列表类型的 API 支持前端排序

个人不建议3，因为依然无法保证关键词顺序一定，后期增加关键词还可能打乱顺序（e.g., "所有“-”所有歌曲“-”所有电台“ vs ”所有电台“-”所有“-”所有歌曲“）
