### ISSUE TITLE
歌曲名简繁转换

### ISSUE THREAD

**Issue by flymin** [hanxi/xiaomusic#189]
pt 上下载的好多资源用繁体名称，是否可以加个简繁转换搜索？

只在 `fuzzyfinder` 和 `find_best_match` 内部转换下就可以（类似 `lower`），用 [opencc](https://github.com/yichen0831/opencc-python) 几行代码就能实现。我本地试了感觉没问题。

**Comment by hanxi** [comment]
小爱音箱的对话记录应该是简体吧，可以接入。
