### ISSUE TITLE
音频文件 tag 获取速度慢

### ISSUE THREAD

**Issue by flymin** [hanxi/xiaomusic#190]
目前 `get_audio_metadata` 这个函数太慢了，我的曲库 7000+ 文件初始化需要 15+min。

是不是可以加个本地字典缓存？访问过的文件就跳过

**Comment by hanxi** [comment]
可以加个 json 文件缓存下，启动时先加载json文件，全部处理完最后要清理不存在的歌曲缓存。

**Comment by hanxi** [comment]
还需要加个清理这个缓存文件的接口，可能存在文件名没变时，标签修改了的情况。

**Comment by flymin** [comment]
> 还需要加个清理这个缓存文件的接口，可能存在文件名没变时，标签修改了的情况。

对得加这个，不过我有点搞不来前端的接口

**Comment by hanxi** [comment]
前端加个按钮就行，前端可以等我加也行。

**Comment by flymin** [comment]
想问下本项目静态缓存应该放在哪里呢？持久目录好像只有 conf 和 music，都不太合适？

**Comment by hanxi** [comment]
可以新增一个 cache 目录，没设置时也可以默认用 conf 目录。

**Comment by hanxi** [comment]
我改了一下，直接默认就cache了。

**Comment by F-loat** [comment]
启动的时候获取所有的 tag 会不会太重了，在查询的时候再获取可以吗

**Comment by flymin** [comment]
主要的问题应该就是主进程等待，要改的话，感觉改成异步最合适，单独剥离一个更新函数，不放在 `_gen_all_music_list` 里面做

**Comment by flymin** [comment]
我刚看了下我本地的 tag cache 文件有 2.2G，是不是得精简一下

**Comment by hanxi** [comment]
这么大的啊，看来是我歌少。一个歌曲一个cache文件好像也不太合适，每次都io也耗时，纠结要不要上数据库，我先找找有没有那种文件缓存库吧。

**Comment by hanxi** [comment]
是不是不存cache文件比较简单？而是用个LRU缓存固定个数，每次请求时才去提取存到LRU里。

**Comment by hanxi** [comment]
@flymin 你注释下歌词和图片信息看看缓存文件有多大？

**Comment by flymin** [comment]
去掉图片就可以，我删了那三行 `b64encode`，现在 cache 文件 5.8M

**Comment by hanxi** [comment]
那图片只能改成实时读取了。

**Comment by flymin** [comment]
我理解图片的意义在于前端显示？那是不是要缓存到本地，就是直接存成独立的图片，才能给前端 url 来访问？

只存路径的话程序内存占用也不会有啥问题了

**Comment by hanxi** [comment]
> 我理解图片的意义在于前端显示？那是不是要缓存到本地，就是直接存成独立的图片，才能给前端 url 来访问？
> 
> 只存路径的话程序内存占用也不会有啥问题了

好像有道理，图片确实可以存文件，这样也是可以一次性生成。可以做成内存放存图片的路径，类似歌曲路径一样，在前端请求时拼接好url就行。图片不能存到一个目录里，防止出现单目录文件数量过大的问题，也可以可以沿用歌曲文件的路径结构。比如 cache/picture/ 开头，后面的目录跟歌曲目录一致即可。

**Comment by hanxi** [comment]
@F-loat @52fisher 可能会把歌曲的图片信息改为url，你们觉得呢？base64和url哪种更合适？

**Comment by F-loat** [comment]
url 没问题的，不是实时获取的话没必要用 base64 了

**Comment by 52fisher** [comment]
> 好像有道理，图片确实可以存文件，这样也是可以一次性生成。可以做成内存放存图片的路径，类似歌曲路径一样，在前端请求时拼接好url就行。图片不能存到一个目录里，防止出现单目录文件数量过大的问题，也可以可以沿用歌曲文件的路径结构。比如 cache/picture/ 开头，后面的目录跟歌曲目录一致即可。

Base64只需要通过musictag=true请求一次，但如果说有性能问题的话，存URL也可以。不过这样就要连续发送两次请求。现在的设计是做了信息懒加载，只有出现在视口的才发送请求获取歌曲信息，同时加载封面。视口范围内要同时展示6到9个歌曲，这样发送的请求数量可能有点多，对比以前数量要乘以二了。不过每个请求都是异步的，就是不知道能不能响应过来。

存文件的话，接口返回效率应该会高很多。封面的缓存路径最好做扁平化设计，可以对filename或者pathname做hash，然后slice(-6)，这样能解决路径特别长的问题。不过缺点也很明显，就是封面数据要占很大的存储空间，尤其是存了好几千几万首。现在能做的也就只有空间换时间了吧

**Comment by 52fisher** [comment]
> 我理解图片的意义在于前端显示？那是不是要缓存到本地，就是直接存成独立的图片，才能给前端 url 来访问？
> 
> 只存路径的话程序内存占用也不会有啥问题了

@flymin 存本地的时候不要直接存原来的二进制数据。元数据里面的图片尺寸都特别的大，有3000×3000，1400×1400的，最好压缩一下，按宽度300px等比缩放。

**Comment by 52fisher** [comment]
> 去掉图片就可以，我删了那三行 `b64encode`，现在 cache 文件 5.8M

返回base64的话，图片压缩一下再转base64行不行。你看一下如果压缩图片到300 px再存到内存里面，我感觉这样子内存占用最多就四五百M

**Comment by F-loat** [comment]
base64 本身就比二进制要大，传输效率不如用 url 的，我之前看好像新加了个带 tag 的列表接口，需要在列表里展示图片的话直接用新接口吧，图片做懒加载就好

**Comment by hanxi** [comment]
是的，新接口都还没发版本，这个版本不着急发。

**Comment by 52fisher** [comment]
在保证性能的情况下，URL返回base 64或者地址都可以。其实对前端影响不大，就是发送请求等待返回而已，再发一次请求对懒加载也没啥影响。图片存文件可以直接存300 px的，同时发送六个请求再加上及时压缩的话，接口返回的时间肯定要变长。就算播放组件全屏化，300 px也完全足够了。直接把文件存死就行，不过存的时候注意一下保持比例不变

**Comment by 52fisher** [comment]
其实我觉得给URL最好.  因为base64返回到编码真的太长了。我昨晚做了一个多小时的优化，没*用.  当前播放的音乐信息要缓存上，但是base64占用的空间太大，加上已经缓存的列表信息。localStorage本身就只有5M到10M的空间，直接爆炸了

**Comment by hanxi** [comment]
还差个图片等比缩小到300px的逻辑。

**Comment by hanxi** [comment]
@flymin 有空可以更新看看，重新生成看json文件有多大，也看看图片目录有多大。

**Comment by flymin** [comment]
没问题，json 6M，图片目录 62M
