### ISSUE TITLE
希望歌曲下载处可以批量，每行一首歌，这样一次性可以下载一个歌单了

### ISSUE THREAD

**Issue by dludream** [hanxi/xiaomusic#191]
![微信截图_20240922111051](https://github.com/user-attachments/assets/03253c41-3ec1-4e09-8e94-353f0b390c4f)

希望歌曲下载处可以批量，每行一首歌，这样一次性可以下载一个歌单了

**Comment by hanxi** [comment]
有人提过，还没空实现。

**Comment by hanxi** [comment]
下载歌单命令 
```
yt-dlp --output "%(playlist)s/%(title)s.%(ext)s" --extract-audio --audio-format mp3 --embed-thumbnail --add-metadata "https://www.bilibili.com/playlist/PLXXXXXX"
```

**Comment by lazybabyz** [comment]
> 下載歌單指令
> 
> ```
> yt-dlp --output "%(playlist)s/%(title)s.%(ext)s" --extract-audio --audio-format mp3 --embed-thumbnail --add-metadata "https://www.bilibili.com/playlist/PLXXXXXX"
> ```
> 
> 意思是：
> 
> ```
> yt-dlp --yes-playlist -x --audio-format mp3 --output "%(title)s.%(ext)s" "https://m.bilibili.com/video/BV1WUsDezE88"
> ```
谢谢大佬 请问在哪个位置输入这个命令

**Comment by hanxi** [comment]
> > 下載歌單指令
> > ```
> > yt-dlp --output "%(playlist)s/%(title)s.%(ext)s" --extract-audio --audio-format mp3 --embed-thumbnail --add-metadata "https://www.bilibili.com/playlist/PLXXXXXX"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 意思是：
> > ```
> > yt-dlp --yes-playlist -x --audio-format mp3 --output "%(title)s.%(ext)s" "https://m.bilibili.com/video/BV1WUsDezE88"
> > ```
> 
> 谢谢大佬 请问在哪个位置输入这个命令

等0.3.38版本吧，会有个界面可以下载。
