### ISSUE TITLE
L05C 需要 MiIOService 才能 tts 发声

### ISSUE THREAD

**Issue by flymin** [hanxi/xiaomusic#196]
我的 L05C 用默认的 tts 无法发声，歌曲播放都正常。

我可以加一个 MiIOService 的 tts 吗？需要 config 里面加个选项来确定具体的 command，为空就用默认的 MiNAService

**Comment by hanxi** [comment]
https://github.com/hanxi/xiaomusic/issues/112

这里之前讨论过，我之前的想法是用别的工具把文字生成mp3文件然后再播放，不确定效果怎么样。

MiIOService最初是引入了的，后面以为没啥用被我干掉了，然后我也没有 L05C 没法测试。你可以直接参考 xiaogpt 加回来试试的，翻看旧代码也能找到。

**Comment by hanxi** [comment]
如果把 MiIOService 弄回来了，也可以把声音接口加上试试，目前声音接口有bug，可能要两个接口同时调用才能解决。
