### ISSUE TITLE
音乐 API 加密访问

### ISSUE THREAD

**Issue by flymin** [hanxi/xiaomusic#197]
目前没有 verification 的 api 是否可以实现类似 https://github.com/halverneus/static-file-server 这个项目的文件加密访问？

具体形式为：
```
# Use key / code parameter in the request URL for access control. The code is
# computed by requested PATH and your key.
# Example:
#   ACCESS_KEY=username
#   To access your file, either access:
#   http://$HOST:$PORT/my/place/my.file?key=username
#   or access (md5sum of "/my/place/my.fileusername"):
#   http://$HOST:$PORT/my/place/my.file?code=44356A355E89D9EE7B2D5687E48024B0
ACCESS_KEY=
```

不知道小爱是否支持加参数的链接访问？

**Comment by hanxi** [comment]
你可以试试改下 music_file 接口，限定 accesskey 参数正确才允许访问，然后播放测试链接时带上参数看看能不能播放。

还可以试试目前支持的 Basic Auth 格式是否可行， http://username:password@hostname:8090/music/ 类似这种格式，然后要把 music_file 的 Verifcation=Depends(verification) 加上，如果 Basic Auth 链接可以的话，建议采用这个更通用。

**Comment by flymin** [comment]
ok 我有空了都试下

**Comment by flymin** [comment]
Basic Auth 好像不行，直接从 log 里面复制 url 到浏览器是可以访问的，小爱访问后端就报 401。大佬可以检查下实现。

URL 参数可以，小爱能直接播放我 file server 的加密链接。

**Comment by hanxi** [comment]
改法没问题，那就是小爱音箱不支持这种链接。URL 加参数是否可以直接用现有的 username + password 生成一个 hash 值用作 accesskey ? 这样就不用新增配置了，判断开启了认证就检查一下 accesskey 。

**Comment by hanxi** [comment]
同样开启了认证时才返回有 accesskey 的链接？

**Comment by hanxi** [comment]
accesskey 可以缓存到内存中，就不用每次请求都去计算一遍。比如 `xiaomusic.accesskey` 这种。

**Comment by flymin** [comment]
accesskey 直接用 username + password 没问题。

只是实现中推荐用 accesscode 访问，也就是请求的地址+accesskey 计算得到的 md5，起到隐藏 accesskey 的目的。这样会更安全。目前应该只有 music 需要靠这个做访问限制，计算 accesscode 的时间基本可以忽略不计。

**Comment by hanxi** [comment]
那动态计算也行，

**Comment by flymin** [comment]
好嘞
