### ISSUE TITLE
请允许proxy为空

### ISSUE THREAD

**Issue by dzhuang** [hanxi/xiaomusic#2]
proxy写入了一个默认值，所以下面的`validate_proxy`一定会运行.

https://github.com/hanxi/xiaomusic/blob/7e7bb256b52240eca4cf8d0f178acd0318fe8011/xiaomusic/config.py#L59-L63

**Comment by dzhuang** [comment]
> 是否需要改成 proxy: str|None 这样的语法？

有type checking当然会更好！

**Comment by JoeNik** [comment]
http代理带账号密码的是不是不行？

**Comment by hanxi** [comment]
> http代理带账号密码的是不是不行？

@JoeNik 

可以的，参考yt-dlp的说明文档:

```
Use the specified HTTP/HTTPS/SOCKS proxy. To
enable SOCKS proxy, specify a proper scheme,
e.g. socks5://user:pass@127.0.0.1:1080/.
Pass in an empty string (--proxy "") for
direct connection
```
