### ISSUE TITLE
小米音箱在播放时候会亮着灯，如何能设置让他关闭呢？

### ISSUE THREAD

**Issue by zhanggaolei001** [hanxi/xiaomusic#21]
设备小米音箱pro，
另外我发现小米音箱会莫名其妙突然自己唱起歌来，语音或web页面“关机”后一段时间也会出现，不知道是不是个例。

**Comment by hanxi** [comment]
好像我的红米也会亮着灯。

**Comment by hanxi** [comment]
突然唱歌我也遇到过，没摸清楚具体原因。

**Comment by wudingjian** [comment]
播放过程中，我也亮着灯

**Comment by zhanggaolei001** [comment]
小爱音箱自己偷偷播放的现象总结:
我发现如果"关机"/"停止播放"后,如果不关闭WebUI,则会发生自动再次播放的问题,如果把网页关掉,就不会再自动播放了;
用的IOS的Safari浏览器,浏览器最小化,手机锁屏,均会出现;
希望能有助于定位问题。

**Comment by liuchenger** [comment]
楼主的设备型号是LX06还是L06A，想淘个二手的用用

**Comment by hanxi** [comment]
> 楼主的设备型号是LX06还是L06A，想淘个二手的用用

我的是 L07A ，红米的

**Comment by wxxcarl** [comment]
我现在就是因为突然自动播放，所以不敢用了，会把家里人吓死。。。万一半夜突然播放，那更加 :zap:

**Comment by hanxi** [comment]
@firstuanl main tag 更新了，有空帮忙测测吗？
```
docker pull hanxi/xiaomusic:main
```

**Comment by firstuanl** [comment]
> @firstuanl main tag 更新了，有空帮忙测测吗？
> 
> ```
> docker pull hanxi/xiaomusic:main
> ```

大佬，哪个文件，我是用源码运行的。晚上试下。

**Comment by wxxcarl** [comment]
是修复了亮灯问题还是莫名自己唱歌的问题？

**Comment by hanxi** [comment]
> > @firstuanl main tag 更新了，有空帮忙测测吗？
> > ```
> > docker pull hanxi/xiaomusic:main
> > ```
> 
> 大佬，哪个文件，我是用源码运行的。晚上试下。

是更新的依赖库，你用 pdm update 更新试下。

**Comment by hanxi** [comment]
> 是修复了亮灯问题还是莫名自己唱歌的问题？

自动播放的我还没摸索出来，用网页里的关机按钮应该是能正常关机的。上面是说修复了亮灯的问题。

**Comment by firstuanl** [comment]
还是会亮灯，

gpt确定是不会亮。

今天在windows10下见一bug
INFO     Serving on 0.0.0.0:8090                                                   httpserver.py:82
                    INFO     Running xiaomusic now,                                                    xiaomusic.py:439
                             ?`????/???/???/????/????/????/??/????/???
                             ??/set_volume#`?????
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8090
 * Running on http://192.168.2.161:8090
 

 "GET /playingmusic HTTP/1.1" 200 -
[download] Finished downloading playlist: ??? - ???
[05/14/24 22:51:49] INFO     cur_music ??? - ???                                                 xiaomusic.py:522
                    INFO     ??                                                                      xiaomusic.py:524
                             http://192.168.2.5:8090/music%5C%E5%91%A8%E6%9D%B0%E4%BC%A6%20-%20%E4%B8%
                             9C%E9%A3%8E%E7%A0%B4.mp3
                    INFO     ???????                                                            xiaomusic.py:527
                    INFO     ?? ??? - ??? : music\??? - ???.mp3 ??? 310 ?            xiaomusic.py:416
                    INFO     310?????????

已设置ip,且显示，但播放ip不对

**Comment by firstuanl** [comment]
直接在connfigpy里设置ip,

路径符号好像还是不对
??                                                                      xiaomusic.py:524
                             http://192.168.2.161:8090/music%5C%E9%83%AD%E9%A1%B6%20-%20%E5%87%84%E7%B
                             E%8E%E5%9C%B0.mp3
192.168.2.245 - - [14/May/2024 23:09:17] "GET /music\\??%20-%20???.mp3 HTTP/1.1" 404 -
                    INFO     ???????                                                            xiaomusic.py:527
192.168.2.245 - - [14/May/2024 23:09:17] "GET /music\\??%20-%20???.mp3 HTTP/1.0" 404 -
                    INFO     ?? ?? - ??? : mu

**Comment by hanxi** [comment]
@firstuanl music后面少了/

**Comment by firstuanl** [comment]
大佬在外国啊，

ubuntu下是正常的，windows下感觉路径的斜杆不对。

config.py没有S12, 我加进就可以语音控制了。

**Comment by zhanggaolei001** [comment]
> 楼主的设备型号是LX06还是L06A，想淘个二手的用用

我的是L07A,小米音箱pro,就是高高的那个,带红外遥控和蓝牙的那个

**Comment by firstuanl** [comment]
> > 大佬在外国啊，
> > ubuntu下是正常的，windows下感觉路径的斜杆不对。
> > config.py没有S12, 我加进就可以语音控制了。
> 
> 设备类型新增的可以帮忙提个pr吗？

大佬怎么pr？我是看xiaogpt抄过来的。

**Comment by hanxi** [comment]
@firstuanl fork 这个工程，然后修改代码提交到自己仓库，然后提pr给我合并。可以看看别人写的教程 https://zhuanlan.zhihu.com/p/584834288?utm_id=0

**Comment by hanxi** [comment]
我的设备修改参数为2不会亮灯，有兴趣的可以试试自己的设备。修改 type 用 micli play 命令测试。

https://github.com/yihong0618/MiService/issues/30

**Comment by firstuanl** [comment]
> 我的设备修改参数为 2 不会亮灯，有兴趣的可以试试自己的设备。修改 type 用 micli play 命令测试。
> 
> [yihong0618/MiService#30](https://github.com/yihong0618/MiService/issues/30)

灯不亮了。

默认音量在哪里，默认打开50,平常只用20

**Comment by hanxi** [comment]
播放时量灯问题已解决。
