### ISSUE TITLE
设备无法找到？

### ISSUE THREAD

**Issue by xpyob** [hanxi/xiaomusic#215]
我在conf即setting.json里设置了mi_did": "L16A",但是在在操控面板里无法找到设备。如何解决，请教了，谢谢！

**Comment by hanxi** [comment]
> 我在conf即setting.json里设置了mi_did": "L16A",但是在在操控面板里无法找到设备。如何解决，请教了，谢谢！

不要自己设置，后台设置小米账号密码后，勾选设备就会有。另外did不是设备型号，是一串数字。

**Comment by xpyob** [comment]
我在后台设置了小米账号密码，但是设备就是无法显示。另外did可以不用填写吧？

**Comment by hanxi** [comment]
> 我在后台设置了小米账号密码，但是设备就是无法显示。另外did可以不用填写吧？

那就是登陆失败的问题，去看 FAQ 里的步骤。did 不用自己填。

**Comment by hanxi** [comment]
> 谢谢，小米音箱登录账号和密码确认无误，查了一下日志如下： https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_ahDuXYcLQ2EmZNoyRVIzs0rbjFOvt6: Login failed Traceback (most recent call last): File "/app/xiaomusic/xiaomusic.py", line 914, in getalldevices device_list = await self.mina_service.device_list() File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 54, in device_list result = await self.mina_request("/admin/v2/device_list?master=" + str(master)) File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 49, in mina_request return await self.account.mi_request( File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request raise Exception(f"Error {url}: {resp}") Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_ahDuXYcLQ2EmZNoyRVIzs0rbjFOvt6: Login failed [02:57:43] [0.3.37] [ERROR] xiaomusic.py:916: Execption Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_ahDuXYcLQ2EmZNoyRVIzs0rbjFOvt6: Login failed Traceback (most recent call last): File "/app/xiaomusic/xiaomusic.py", line 914, in getalldevices device_list = await self.mina_service.device_list() File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 54, in device_list result = await self.mina_request("/admin/v2/device_list?master=" + str(master)) File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 49, in mina_request

看 FAQ 吧，就是登陆失败，用那个方法试试。
