### ISSUE TITLE
请问一下是否可以emby?

### ISSUE THREAD

**Issue by backtracker** [hanxi/xiaomusic#219]
如果想播放指令改成调用emby的api应该怎么做？能否提供一下思路

**Comment by backtracker** [comment]
2年过去了，还没有看到emby的支持，索性自己弄了一个，保留核心，仅支持emby，地址是 https://github.com/backtracker/xiaoemby ，分享给有需要的人

**Comment by hanxi** [comment]
@backtracker 如果可以的话，你可以提个PR的。

**Comment by backtracker** [comment]
@hanxi 改动太多了，我合不进去主线了
