### ISSUE TITLE
建议web中能显示加载到的歌曲、播放列表

### ISSUE THREAD

**Issue by wudingjian** [hanxi/xiaomusic#22]
如题

支持双击播放和或加入列表
支持播放列表播放

**Comment by hanxi** [comment]
这个建议不错，先支持自定义播放列表后再看看怎么设计界面。

**Comment by darkrain88** [comment]
怎么播放本地的目录下面的歌曲呢。 发语音， 他还是试听版

btw  lx05 play能连接。

**Comment by hanxi** [comment]
@darkrain88 
web网页里能播放吗？

**Comment by a904055262** [comment]
作者考虑添加这个功能啊，UI的什么无所谓，能显示文件名列表就行了

**Comment by hanxi** [comment]
> 作者考虑添加这个功能啊，UI的什么无所谓，能显示文件名列表就行了

希望有高手来搞下UI，就像音乐播放器那样的。我主要是没空搞这个，我搞也只能搞出个简陋的版本。

**Comment by darkrain88** [comment]
> @darkrain88 web网页里能播放吗？

能 就是随机播放那种

**Comment by hanxi** [comment]
播放列表功能还不支持，目前支持了在网页里显示当前正在播放的歌曲，也支持了模糊搜索本地歌曲。 @wudingjian 欢迎体验。
![image](https://github.com/hanxi/xiaomusic/assets/1185757/fde1d448-4e0d-4631-aa19-c7ddcf2bf4be)
![image](https://github.com/hanxi/xiaomusic/assets/1185757/66e4ee1e-2c15-4ded-af74-ff584e6e97e9)

**Comment by hanxi** [comment]
等做好播放列表的那个功能就会有接口拿播放列表了。

@gzers 有兴趣可以直接提pr加个接口获取目前将要播放的所有歌曲。

**Comment by hanxi** [comment]
> 或者提供接口可以自己写页面

@gzers 目前已经能显示播放列表了，有啥优化的欢迎 pr
