### ISSUE TITLE
小爱播放本地音乐无声音，可播放链接音乐

### ISSUE THREAD

**Issue by guanli-2024** [hanxi/xiaomusic#220]
![IMG_2537](https://github.com/user-attachments/assets/5dded878-c1bc-4072-9d51-399e0f5f7ffb)

**Comment by hanxi** [comment]
参考FAQ里的解决办法。

**Comment by guanli-2024** [comment]
> 参考FAQ里的解决办法。

昨晚搞了好长时间，突然想起来，家里的小爱单独连了另一个路由器的WiFi，和nas不在一个局域网里。调整以后可以外放音乐了。
