### ISSUE TITLE
bug：第三方UI样式问题

### ISSUE THREAD

**Issue by flymin** [hanxi/xiaomusic#224]
pure：
![Snipaste_2024-10-09_13-24-21](https://github.com/user-attachments/assets/0450f010-3be3-45b6-a315-a4301ddf4206)
![Snipaste_2024-10-09_13-24-49](https://github.com/user-attachments/assets/dc84ba87-d68b-4b2e-8927-1b57ab2fb3f1)

xmusicplayer：
![Snipaste_2024-10-09_13-22-53](https://github.com/user-attachments/assets/8d48d0e0-ec26-44d7-b34c-b05aa9c0a2eb)
![Snipaste_2024-10-09_13-23-05](https://github.com/user-attachments/assets/369e1e76-2946-4817-b0a2-b4fb7effb9af)

**Comment by hanxi** [comment]
pure是适配大屏幕，xplayer是适配手机竖屏。

**Comment by flymin** [comment]
大屏幕也没法满屏显示，而且某些分辨率下图标会错位。

手机屏幕这个兼容性就更差了。。。
