### ISSUE TITLE
请问如何刷新播放列表？

### ISSUE THREAD

**Issue by llldddbbb** [hanxi/xiaomusic#23]
我在目录里手动导入了mp3歌曲，但是这个歌曲一直没有被播放。还有，我手动删除了本地的歌曲，他下一次播放还是会自动把歌曲下载回来，我感觉是播放列表有缓存导致的。请问怎么重刷这个播放列表呢？

**Comment by hanxi** [comment]
点随机播放试试

**Comment by llldddbbb** [comment]
> 点随机播放试试

这个可以了，感谢解答
