### ISSUE TITLE
小米sound(L16A) “播放歌曲“的口令无效

### ISSUE THREAD

**Issue by zaqai** [hanxi/xiaomusic#24]
对小爱说“播放歌曲周杰伦晴天”， 依然是自带的付费音源，后台也不会下载，
但其他一切正常，网页输入歌曲名字点播放，小爱会说“下载XXX”，然后播放
型号L16A

**Comment by zaqai** [comment]
是否支持xiaogpt中“--mute_xiaoai”参数，以及这个参数是否有效

**Comment by hanxi** [comment]
mute_xiaoai 是用来打断小爱当前说话的，默认是 true，不能解决你的问题。你的问题应该是获取不到对话记录，可能是登录失败。你可以看看这个问题能不能解决：https://github.com/yihong0618/MiService/issues/2

**Comment by zaqai** [comment]
> mute_xiaoai 是用来打断小爱当前说话的，默认是 true，不能解决你的问题。你的问题应该是获取不到对话记录，可能是登录失败。你可以看看这个问题能不能解决：[yihong0618/MiService#2](https://github.com/yihong0618/MiService/issues/2)

不太行，我是ubuntu跑的docker，国内ip，在容器内micli list也能打印所有设备啊

**Comment by hanxi** [comment]
@zaqai 你看看是不是 --hardware 参数或者 MI_HARDWARE 环境变量是不是配错了？获取最近的对话记录是需要这个的，我试过改错了就拉不到对话记录，也不会报错。

```python
LATEST_ASK_API = "https://userprofile.mina.mi.com/device_profile/v2/conversation?source=dialogu&hardware={hardware}&timestamp={timestamp}&limit=2"
```

**Comment by zaqai** [comment]
@hanxi 好了好了，还真是MI_HARDWARE参数错了，改命令的时候少删了一位，十分感谢🙏

但现在说完命令他是先播放自带的音乐，然后后台音乐下载完再播下载的，也是正常的吗

**Comment by hanxi** [comment]
> @hanxi 好了好了，还真是MI_HARDWARE参数错了，改命令的时候少删了一位，十分感谢🙏
> 
> 但现在说完命令他是先播放自带的音乐，然后后台音乐下载完再播下载的，也是正常的吗

下载需要时间，算正常吧。

**Comment by hd-samcui** [comment]
我的小米是L06C，后台能看到在播放，后台调整音量喇叭有提示音，当时播放的音乐，喇叭不发声。当然语音指令播放本地节目也是不管用的，不过从网上下载一个mp3回来。
