### ISSUE TITLE
XMusicPlayers主题手机端不能后台播放

### ISSUE THREAD

**Issue by lishx8888** [hanxi/xiaomusic#240]

**Comment by lishx8888** [comment]
。

**Comment by hanxi** [comment]
估计是浏览器的问题？试试chrome?

**Comment by hanxi** [comment]
已测试手机版的 chrome 可以后台播放。

**Comment by hanxi** [comment]
@52fisher 好像是有点问题，不会继续播放下一首。

**Comment by hanxi** [comment]
@lishx8888 先用edge浏览器吧，可以后台。

**Comment by 52fisher** [comment]
安卓WebView内核的bug问题
更新到44版本 试一下 应该解决了

**Comment by Lonely-Sit** [comment]
> 安卓WebView内核的bug问题 更新到44版本 试一下 应该解决了

我也遇到了此问题 使用其他浏览器可以 我使用Google Play更新了版本 商店中显示为最新版 但还是无法播放
