### ISSUE TITLE
我用的cloudflare tunnels反代的域名，反代本身就带了端口号，怎么能让播放的时候域名后面不跟端口号呢？

### ISSUE THREAD

**Issue by Don-Jade** [hanxi/xiaomusic#245]
<img width="451" alt="1729665483426" src="https://github.com/user-attachments/assets/42cc87a3-ec71-4ced-8c43-e20609844e53">
这个域名后面的端口号怎么能不带上

**Comment by hanxi** [comment]
没理解你的问题，你反代端口是 443 还是其他的？

**Comment by Don-Jade** [comment]
反代的8090  用***.xyz/music/***************就能播放  
但是现在点播放是***.xyz:8090/music/*********

**Comment by Don-Jade** [comment]
cloudflare tunnels的反代是  xiaomusic.***.xyz    →→→    192.168.*.*：8090

**Comment by Don-Jade** [comment]
谢谢！
