### ISSUE TITLE
播放有声剧顺序的问题

### ISSUE THREAD

**Issue by tanmx** [hanxi/xiaomusic#249]
下载了一些有声儿童剧，文件的命名为 1，2，3，4……有的剧情有上下集，但是用小爱音箱播放的时候还是有点问题

1.手动选择播放第一集 1.xxx，点击下一集会播放第10集 10.xxxxx
2.手动选择播放第2集 2.xxx，点击下一集会播放第20集 20.xxxxx
这应该是一个排序的问题

播放第2集
<img width="1465" alt="image" src="https://github.com/user-attachments/assets/b1a1136e-9899-4fce-8ee8-645bd20f55bc">
手动点击下一首，跳转到20集
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/07f43d21-8340-4114-a487-eb579d4dccd8">

**Comment by zzy19868** [comment]
在前面补0，所有集数数字长度一致，比如001、002

**Comment by tanmx** [comment]
> 在前面补0，所有集数数字长度一致，比如001、002

我临时是这么解决的，手动处理文件名 补0了

**Comment by zzy19868** [comment]
> > 在前面补0，所有集数数字长度一致，比如001、002
> 
> 我临时是这么解决的，手动处理文件名 补0了

用ReNamer软件，有自动补零填充功能。

**Comment by tanmx** [comment]
> > > 在前面补0，所有集数数字长度一致，比如001、002
> > 
> > 
> > 我临时是这么解决的，手动处理文件名 补0了
> 
> 用ReNamer软件，有自动补零填充功能。

学习了，我找chatgpt写的python 原来还有更简单的方法
