### ISSUE TITLE
音乐播放不完整

### ISSUE THREAD

**Issue by ShileiShen** [hanxi/xiaomusic#252]
音箱型号：L05C

问题：该音箱不支持flac格式音乐播放，所以打开了 转换mp3 选项，发现每次音乐都播放不完整就切到下一首歌了。

原因：是因为转换mp3需要时间，而这段时间被算在了播放时间中，导致音乐播放不完整。

麻烦大佬看看有什么好的解决办法吗？

![image](https://github.com/user-attachments/assets/c971e7df-8c42-41c4-8e36-8d83e4b16649)

**Comment by hanxi** [comment]
后台有个设置 【下一首歌延迟播放秒数:】，默认值是 3 ，你可以设大一点，或者自己用工具批量转 mp3 。

**Comment by ShileiShen** [comment]
好的 谢谢
