### ISSUE TITLE
小爱播放一个NAS没有的歌曲时，会继续播放上一个NAS已有的歌曲

### ISSUE THREAD

**Issue by edwinhuish** [hanxi/xiaomusic#253]
取消下载后，播放NAS已有的歌曲后，再喊小爱播放一个NAS没有的歌曲时，会继续播放上一个NAS已有的歌曲，而不是播放小爱自身的网络歌曲。

**Comment by hanxi** [comment]
如果想要小爱音箱播放自身的网络歌曲，请不要用播放歌曲开头。可以用播放音乐开头来播放小爱音箱自身的网络歌曲的。
