### ISSUE TITLE
返回的播放链接有问题

### ISSUE THREAD

**Issue by linsongGong** [hanxi/xiaomusic#254]
如果XIAOMUSIC_HOSTNAME设置为域名加端口形式，返回的播放链接有问题，会多拼上一个端口。
![image](https://github.com/user-attachments/assets/e5328abe-f1cc-4609-83f1-d7640cf3b3f4)

**Comment by hanxi** [comment]
XIAOMUSIC_HOSTNAME不要加端口

**Comment by hanxi** [comment]
外网端口是另一个配置

**Comment by linsongGong** [comment]
好的
