### ISSUE TITLE
语音唤醒播放歌曲后，延迟很高，需要90S以上才能播放

### ISSUE THREAD

**Issue by 1099692751** [hanxi/xiaomusic#256]
音箱型号：小爱音箱Play-L05B
主机：群晖NAS
问题：语音唤醒播放歌曲后，延迟很高，需要90S以上才能播放，打印日志查看，貌似拉取音箱对话记录比较慢，不知道是什么原因？

**Comment by hanxi** [comment]
使用网页点击按钮播放需要多久？

**Comment by 1099692751** [comment]
网页点击按钮播放立刻可以播放，现在歌曲已经下载好的情况下，看大日志上拉取到对话比较滞后

**Comment by 1099692751** [comment]
![image](https://github.com/user-attachments/assets/537ffeb8-6ca7-44d6-96fc-d1e514cd7196)
日志里每个操作都是重复打印很多次正常吗

**Comment by 1099692751** [comment]
![image](https://github.com/user-attachments/assets/e1142d5f-53e7-4619-a81f-3515125b0ec4)
还看到这个

**Comment by hanxi** [comment]
看日志都正常

**Comment by 1099692751** [comment]
可能是我的IP被小米限制了，怎么折腾延迟都很高，最低1分钟 @hanxi

**Comment by 1099692751** [comment]
谢谢作者
