### ISSUE TITLE
支持多个音箱

### ISSUE THREAD

**Issue by on8on** [hanxi/xiaomusic#26]
能否将MI_DID和MI_HARDWARE类型为list，这样可以多个音箱一起使用

**Comment by hanxi** [comment]
好像有人提过，应该是能实现的。

**Comment by zhanggaolei001** [comment]
我试过开两个docker,用俩端口,也能用起来

**Comment by hanxi** [comment]
楼主想要的效果是两个音箱同时播放同一首歌吗？

**Comment by vary** [comment]
我也有这个需求，不一定同时播放，就是都可以播放本地或者搜索播放就行

**Comment by hanxi** [comment]
不是同时播放的话，可以改dockerfile实现，或者像楼上说的开两个。

**Comment by sykeswzq** [comment]
> 我试过开两个docker,用俩端口,也能用起来

2个docker能共用一个下载文件夹吗？

**Comment by sykeswzq** [comment]
> 不是同时播放的话，可以改dockerfile实现，或者像楼上说的开两个。

不是同时播放，是分别播放，共用一个下载文件夹

**Comment by hanxi** [comment]
@sykeswzq 可以的，用不同的端口就行。目录可以映射同一个。应该就是改端口参数，did和设备类型那些就可以。

**Comment by sykeswzq** [comment]
> @sykeswzq 可以的，用不同的端口就行。目录可以映射同一个。应该就是改端口参数，did和设备类型那些就可以。

did怎么获取呀，小爱后面？

**Comment by hanxi** [comment]
@sykeswzq 用 https://github.com/yihong0618/MiService

**Comment by sykeswzq** [comment]
> @sykeswzq 用 https://github.com/yihong0618/MiService

搞定了，建了2个docker 2个端口，不用did也能用。
