### ISSUE TITLE
方便制作一个基于arm64架构的镜像吗

### ISSUE THREAD

**Issue by zhu-jie-tester** [hanxi/xiaomusic#260]
方便制作一个基于arm64架构的镜像吗

**Comment by hanxi** [comment]
![image](https://github.com/user-attachments/assets/63d740bc-8c12-451e-8f92-fbc184f98bdb)
已经有arm64的镜像

**Comment by wcwtfhvk** [comment]
我在树莓派上搭建成功了arm可以的pip和docker都能用
