### ISSUE TITLE
新增 ID3 标签更新接口

### ISSUE THREAD

**Issue by F-loat** [hanxi/xiaomusic#266]
[小程序](https://github.com/F-loat/xiaoplayer)里可以联网获取本地没有的歌词及封面，希望可以持久化到文件中，避免每次重复获取

**Comment by F-loat** [comment]
我看是更新到缓存里了，考不考虑加个开关直接写入文件 @hanxi，这样约等于支持刮削了，优先级不高

**Comment by hanxi** [comment]
> 我看是更新到缓存里了，考不考虑加个开关直接写入文件 @hanxi，这样约等于支持刮削了，优先级不高

考虑加个选项控制是否写入，默认不写入。改用户的文件需要谨慎一点。

**Comment by F-loat** [comment]
@hanxi 小程序体验版已经加上了，请求参数大概这样, 接口调用响应正常

``` json
{
  "album": "梦游计",
  "artist": "许嵩",
  "lyrics": "[ti:全球变冷]↵[ar:许嵩]↵[al:梦游计]",
  "musicname": "许嵩 - 全球变冷",
  "picture": "data:image/png;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/",
  "title": "全球变冷",
  "year": "2012-07-11"
}
```

**Comment by hanxi** [comment]
> @hanxi 小程序体验版已经加上了，请求参数大概这样，接口调用响应正常
> 
> ```json
> {
>   "album": "梦游计",
>   "artist": "许嵩",
>   "lyrics": "[ti:全球变冷]↵[ar:许嵩]↵[al:梦游计]",
>   "musicname": "许嵩 - 全球变冷",
>   "picture": "data:image/png;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/",
>   "title": "全球变冷",
>   "year": "2012-07-11"
> }
> ```

图片有点问题，base64 我没剔除前面那些字符串，我下个版本支持下吧。

**Comment by F-loat** [comment]
@hanxi 我这边改也行，那个前缀也是我额外拼的，可以看下规范是什么样的，其他软件能读取就行

**Comment by F-loat** [comment]
我改吧，简单搜了下好像是不加那些前缀的
