### ISSUE TITLE
语音口令只能是播放歌曲吗

### ISSUE THREAD

**Issue by Yumega** [hanxi/xiaomusic#268]
喜欢听广播，语音口令是不是可以改成播放广播xxx 或者直播改成播放xxx

**Comment by hanxi** [comment]
播放歌曲+广播名字就行，前提是自己先配置好广播电台的歌单。

**Comment by hanxi** [comment]
> 😊 我想 小爱同学 播放广播 凤凰资讯 播放歌曲 凤凰资讯 好别扭

后台可以加口令前缀的，用逗号分割。
