### ISSUE TITLE
play增强版果然是残废

### ISSUE THREAD

**Issue by baiqianlover** [hanxi/xiaomusic#27]
部署正常，play增强版无法使用。包括homeassistant中的音乐play增强版都没法用。型号代码  L05C
![微信截图_20240307211727](https://github.com/hanxi/xiaomusic/assets/26249676/cb53082d-047b-481c-ab9c-c3f6f1f1b507)

![微信截图_20240307211124](https://github.com/hanxi/xiaomusic/assets/26249676/aae67e78-6cf7-414a-90f2-59ec71008799)

**Comment by hanxi** [comment]
这个型号别人也说无法播放，这个机子可以在米家里控制播放吗？如果有能力可以爬接口试试。

**Comment by hanxi** [comment]
那只能等有能力和设备的人搞了。

**Comment by vary** [comment]
触屏音箱LX04也无法播放

**Comment by tianjiao96176** [comment]
> 这个模型别人也说无法播放，这个机子可以在米家里控制播放吗？如果有能力可以爬接口尝试。

我的也是小爱PALY增强版，和楼主一样的问题，docker能正常跑起来，小爱没声音。但是在homeassistant里面，TTS却可以让小爱发声音，Xiaomi Miot Auto: Intelligent speaker。

**Comment by hanxi** [comment]
发声音估计是用的命令模式，放音乐得用api接口。

**Comment by tianjiao96176** [comment]
https://github.com/zanjie1999/httpRandomMusic  你试试这个，这哥貌似是play增强版。

**Comment by tianjiao96176** [comment]
> 发声音估计是用的命令模式，放音乐得用api接口。

https://github.com/zanjie1999/httpRandomMusic   这个也许能用

**Comment by baiqianlover** [comment]
我是域名死活劫持不上，问过那个开发者。说现在还要tcp劫持，奈何能力有限。我就放弃了。

**Comment by baiqianlover** [comment]
> > 发声音估计是用的命令模式，放音乐得用api接口。
> 
> https://github.com/zanjie1999/httpRandomMusic 这个也许能用

我是域名死活劫持不上，问过那个开发者。说现在还要tcp劫持，奈何能力有限。我就放弃了。

**Comment by tianjiao96176** [comment]
> > > 发声音估计是用的命令模式，放音乐得用api接口。
> > 
> > 
> > https://github.com/zanjie1999/httpRandomMusic 这个也许能用
> 
> 我是域名死活劫持不上，问过那个开发者。说现在还要tcp劫持，奈何能力有限。我就放弃了。

有时间了我研究下

**Comment by firstuanl** [comment]
小米标准版有可以的吗

**Comment by baiqianlover** [comment]
> 小米标准版有可以的吗

需要你自己测试下

**Comment by firstuanl** [comment]
> > 小米标准版有可以的吗
> 
> 需要你自己测试下

登陆不进去，不知哪没搞好

**Comment by wangwy1015** [comment]
> > > 发声音估计是用的命令模式，放音乐得用api接口。
> > 
> > 
> > https://github.com/zanjie1999/httpRandomMusic 这个也许能用
> 
> 我是域名死活劫持不上，问过那个开发者。说现在还要tcp劫持，奈何能力有限。我就放弃了。

如果有群辉，可以在群辉上起个dns server，把他说的zyym.ie解析到群辉（运行python）上，路由器dns改成群辉地址就可以了

**Comment by firstuanl** [comment]
config.py 设置 L05C试试

**Comment by brainpeng** [comment]
> 触屏音箱LX04也无法播放

同样lx04,用过这个同httpRandommusic 都不能播放

**Comment by hanxi** [comment]
见 #30
