### ISSUE TITLE
红米小爱触屏音箱8仍然不支持

### ISSUE THREAD

**Issue by sghuenn** [hanxi/xiaomusic#270]
支持列表里有红米小爱触屏音箱8，但实际使用发现，仍然需要打开兼容模式才能使用。不开兼容模式只能调节音量大小，其他功能一概没法用。

**Comment by hanxi** [comment]
> 支持列表里有红米小爱触屏音箱8，但实际使用发现，仍然需要打开兼容模式才能使用。不开兼容模式只能调节音量大小，其他功能一概没法用。

是的，就是要手动开。

**Comment by hanxi** [comment]
型号太多，没找到好办法不用手动维护型号，就让用户自己根据型号去配置了。感兴趣可以去 https://github.com/yihong0618/MiService/blob/main/miservice/minaservice.py#L11 提 pr 把型号加上，然后等更新就行了。
