### ISSUE TITLE
bilisearch下载的音乐不对，换yt-dlp下载也是同样的错误音频

### ISSUE THREAD

**Issue by x64life** [hanxi/xiaomusic#272]
bilisearch和yt-dlp一个源吗？

**Comment by hanxi** [comment]
跟搜索词有关系的，你去b站搜索到的第一个就是你要下载的视频。

**Comment by x64life** [comment]
> 跟搜索词有关系的，你去b站搜索到的第一个就是你要下载的视频。

重新设置bilisearch，这回对了。
我记得配置页面默认是bilisearch，不知道为什么实际通过yt-dlp去下载，所以当我换成yt-dlp还是错的
