### ISSUE TITLE
希望增加一种新的播放列表中歌曲的排列方式 即按照音频文件添加的时间生成播放列表

### ISSUE THREAD

**Issue by tianjiao96176** [hanxi/xiaomusic#273]
当我再用酷我听歌的时候，习惯从最新添加的歌曲开始听。希望小爱音箱也能按照播放的时候也能实现这个功能。

**Comment by dludream** [comment]
这样实现如何？

在music_list增加一个新列表 名为 “新歌曲”，想听新歌就说 播放列表 新歌曲

会从最新的歌曲开始播放。

对应 
`        # 新歌曲
        self.music_list["新歌曲"] = sorted(
            [name for name in self.all_music.keys()],
            key=lambda x: os.path.getctime(self.all_music[x]),
            reverse=True
        )[:50]`

**Comment by hanxi** [comment]
差不多是样子吧，不过歌曲全部放进去也行。还需要排除一下网络歌单里的歌曲。
