### ISSUE TITLE
无法下载歌曲

### ISSUE THREAD

**Issue by icelee123** [hanxi/xiaomusic#279]
[BiliBiliSearch] Playlist 双截棍: Downloading 1 items of 1
[download] Downloading item 1 of 1
[BiliBili] Extracting URL: http://www.bilibili.com/video/av60242330
[BiliBili] 60242330: Downloading webpage
WARNING: [BiliBili] unable to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BiliBili] 60242330: Failed to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[download] Finished downloading playlist: 双截棍

版本:  0.3.49 docker版本

**Comment by hanxi** [comment]
等更新。

**Comment by dludream** [comment]
要用特殊版本的yt，下面这个版本可以正常下载了。
pip install --force-reinstall --break-system-packages git+https://github.com/grqz/yt-dlp.git@ie/bilibili/pi_fallbk

**Comment by hanxi** [comment]
等这个合并后我再更新 https://github.com/yt-dlp/yt-dlp/pull/11667

**Comment by liuhuanlearn** [comment]
> 等这个合并后我再更新 [yt-dlp/yt-dlp#11667](https://github.com/yt-dlp/yt-dlp/pull/11667)

我想说已经合并了，日常催一催，大哥加油
