### ISSUE TITLE
播放失败的问题

### ISSUE THREAD

**Issue by kingszhe9664** [hanxi/xiaomusic#29]
环境是黑裙7.2，使用docker部署。
按照教程操作

HOST_NAME 配置为192.168.0.39 （小爱音箱的IP）
`<html>
<body>

2024/03/09 09:02:19 | stdout |  
-- | -- | --

- 2024/03/09 09:02:19 | stdout | such file or directory: ''
- 2024/03/09 09:02:19 | stdout | mutagen.MutagenError: [Errno 2] No
- 2024/03/09 09:02:19 | stdout | raise MutagenError(e)
- 2024/03/09 09:02:19 | stdout | 272, in _openfile
- 2024/03/09 09:02:19 | stdout | ckages/mutagen/_util.py", line
- 2024/03/09 09:02:19 | stdout | "/app/.venv/lib/python3.10/site-pa
- 2024/03/09 09:02:19 | stdout | File
- 2024/03/09 09:02:19 | stdout | return next(self.gen)
- 2024/03/09 09:02:19 | stdout | lib.py", line 135, in __enter__
- 2024/03/09 09:02:19 | stdout | "/usr/local/lib/python3.10/context
- 2024/03/09 09:02:19 | stdout | File
- 2024/03/09 09:02:19 | stdout | filething, filename, fileobj,
- 2024/03/09 09:02:19 | stdout | with _openfile(None,
- 2024/03/09 09:02:19 | stdout | 162, in wrapper_func
- 2024/03/09 09:02:19 | stdout | ckages/mutagen/_util.py", line
- 2024/03/09 09:02:19 | stdout | "/app/.venv/lib/python3.10/site-pa
- 2024/03/09 09:02:19 | stdout | File
- 2024/03/09 09:02:19 | stdout | audio = mutagen.File(filename)
- 2024/03/09 09:02:19 | stdout | line 402, in get_file_duration
- 2024/03/09 09:02:19 | stdout | "/app/xiaomusic/xiaomusic.py",
- 2024/03/09 09:02:19 | stdout | File
- 2024/03/09 09:02:19 | stdout | e))
- 2024/03/09 09:02:19 | stdout | int(self.get_file_duration(filenam
- 2024/03/09 09:02:19 | stdout | sec =
- 2024/03/09 09:02:19 | stdout | set_next_music_timeout
- 2024/03/09 09:02:19 | stdout | line 410, in
- 2024/03/09 09:02:19 | stdout | "/app/xiaomusic/xiaomusic.py",
- 2024/03/09 09:02:19 | stdout | File
- 2024/03/09 09:02:19 | stdout | self.set_next_music_timeout()
- 2024/03/09 09:02:19 | stdout | line 508, in play
- 2024/03/09 09:02:19 | stdout | "/app/xiaomusic/xiaomusic.py",
- 2024/03/09 09:02:19 | stdout | File
- 2024/03/09 09:02:19 | stdout | await func(arg1=oparg)
- 2024/03/09 09:02:19 | stdout | line 455, in run_forever
- 2024/03/09 09:02:19 | stdout | "/app/xiaomusic/xiaomusic.py",
- 2024/03/09 09:02:19 | stdout | File
- 2024/03/09 09:02:19 | stdout | Traceback (most recent call last):
- 2024/03/09 09:02:19 | stdout |  
- 2024/03/09 09:02:19 | stdout | occurred:
- 2024/03/09 09:02:19 | stdout | exception, another exception
- 2024/03/09 09:02:19 | stdout | During handling of the above
- 2024/03/09 09:02:19 | stdout |  
- 2024/03/09 09:02:19 | stdout | such file or directory: ''
- 2024/03/09 09:02:19 | stdout | FileNotFoundError: [Errno 2] No
- 2024/03/09 09:02:19 | stdout | if writable else "rb")
- 2024/03/09 09:02:19 | stdout | fileobj = open(filename, "rb+"
- 2024/03/09 09:02:19 | stdout | 251, in _openfile
- 2024/03/09 09:02:19 | stdout | ckages/mutagen/_util.py", line
- 2024/03/09 09:02:19 | stdout | "/app/.venv/lib/python3.10/site-pa
- 2024/03/09 09:02:19 | stdout | File
- 2024/03/09 09:02:19 | stdout | Traceback (most recent call last):
- 2024/03/09 09:02:19 | stdout | directory: ''
- 2024/03/09 09:02:19 | stdout | WARNING  执行出错 [Errno 2] No such file or xiaomusic.py:457
- 2024/03/09 09:02:19 | stdout | INFO     已经开始播放了                     xiaomusic.py:506
- 2024/03/09 09:02:19 | stdout | INFO     播放 http://192.168.0.39:8090/     xiaomusic.py:503
- 2024/03/09 09:02:19 | stdout | [03/09/24 01:02:19] INFO     cur_music 奥特曼                   xiaomusic.py:501
- 2024/03/09 09:02:19 | stdout | [download] Finished downloading playlist: 奥特曼
- 2024/03/09 09:02:19 | stdout | [BiliBili] 745273948: Downloading webpage
**- 2024/03/09 09:02:19 | stderr | ERROR: Failed to parse: http://192.168.0.1:80index.asp/**
- 2024/03/09 09:02:19 | stdout | [BiliBili] Extracting URL: http://www.bilibili.com/video/av745273948
- 2024/03/09 09:02:19 | stdout | [download] Downloading item 1 of 1
- 2024/03/09 09:02:19 | stdout | [BiliBiliSearch] Playlist 奥特曼: Downloading 1 items of 1
- 2024/03/09 09:02:18 | stdout | [BiliBiliSearch] 奥特曼: Extracting results from page 1
- 2024/03/09 09:02:18 | stdout | [download] Downloading playlist: 奥特曼
- 2024/03/09 09:02:18 | stdout | [BiliBiliSearch] Extracting URL: bilisearch:奥特曼
- 2024/03/09 09:02:18 | stdout | INFO     正在下载中 奥特曼                  xiaomusic.py:495
- 2024/03/09 09:02:18 | stdout | INFO     do_tts: 正在下载歌曲奥特曼         xiaomusic.py:225
- 2024/03/09 09:02:18 | stdout | opvalue:play oparg:奥特曼
- 2024/03/09 09:02:18 | stdout | [03/09/24 01:02:18] INFO     匹配到指令. opkey:播放歌曲         xiaomusic.py:481
- 

</body>
</html>`

音箱有反应但是马上就中止了，  ERROR: Failed to parse: http://192.168.0.1:80index.asp/  这个ERROR 是什么导致的，我没有配置这个地址 （192.168.0.1为路由器）

**Comment by hanxi** [comment]
HOST_NAME 需要配置 docker 所在的机器的局域网 ip
