### ISSUE TITLE
openwrt的docker运行xiaomusic无法修改挂载目录

### ISSUE THREAD

**Issue by ygqqianzi110** [hanxi/xiaomusic#291]
docker run -p 8090:8090 -v /xiaomusic/music:/mnt/sda1/music -v /xiaomusic/conf:/app/conf m.daocloud.io/docker.io/hanxi/xiaomusic
就是我把音乐目录改为openwrt下挂的硬盘，不行，读取不到，直接用app/music，内存有限

**Comment by hanxi** [comment]
> docker run -p 8090:8090 -v /xiaomusic/music:/mnt/sda1/music -v /xiaomusic/conf:/app/conf m.daocloud.io/docker.io/hanxi/xiaomusic 就是我把音乐目录改为openwrt下挂的硬盘，不行，读取不到，直接用app/music，内存有限

目录映射你写反了。

**Comment by ygqqianzi110** [comment]
好吧，犯了一个低级错误谢谢了
