### ISSUE TITLE
最新版本无法自动下载播放

### ISSUE THREAD

**Issue by KabourWu** [hanxi/xiaomusic#292]
![1733278997347](https://github.com/user-attachments/assets/c9d04950-aa20-442d-8881-f74adc1d514f)

日志显示：2024/12/4 10:22:14  [2024-12-04 10:22:14] [0.3.54] [ERROR] xiaomusic.py:1744: Execption 'XiaoMusicDevice' object has no attribute 'get_hardward'

**Comment by hanxi** [comment]
新版本已经修复，等更新。
