### ISSUE TITLE
L17A 通过网页播放后，无法控制停止播放问题

### ISSUE THREAD

**Issue by brlanweb** [hanxi/xiaomusic#295]
通首次安装本项目过网页控制测试能播放后，
第二天下班回家自动触发播放音乐场景下，
这个时候我通过语音指令告知小爱同学停止播放音乐无效，
音箱不会回复并且音乐会重新开始播放，
直到我打开电脑打开网页点击关机方能结束播放

**Comment by hanxi** [comment]
说【关机】
