### ISSUE TITLE
建议加入酷我的音源，高品质

### ISSUE THREAD

**Issue by ygqqianzi110** [hanxi/xiaomusic#298]
https://bbs.125.la/thread-14761982-1-1.html
这是我看的一个帖子，可以试试，里边都是高品质的音源

**Comment by hanxi** [comment]
有兴趣可以自己写插件，可以参考那个网易云音乐的插件。

**Comment by ygqqianzi110** [comment]
> 有兴趣可以自己写插件，可以参考那个网易云音乐的插件。

不会写才问的哈哈，有版权问题在，确实不能直接加

**Comment by hanxi** [comment]
代码量很少，估计让ai写都能写出来吧。。。
