### ISSUE TITLE
默认主题改版意见征集

### ISSUE THREAD

**Issue by hanxi** [hanxi/xiaomusic#304]
默认主题将会改成这样子，有什么建议吗？可以在测试版本提前体验，docker 镜像版本改为 :main 即可。
![c6784fdd4e8cf75d1ac8e2d7e0892a4](https://github.com/user-attachments/assets/fe2252f5-6bd7-4d79-b1b5-9cb0048ef43b)

**Comment by MOMOTSI** [comment]
大佬 删除键是不是放左边不容易误触

**Comment by hanxi** [comment]
> 大佬 删除键是不是放左边不容易误触

感觉还好吧，有二次弹框确认的。而且那个下拉列表是整行都能点的，不是只能点那个箭头的。

**Comment by hanxi** [comment]
![mmexport1733827858658](https://github.com/user-attachments/assets/fc892650-b21b-4e2b-9c7e-ea17e2299023)

根据群友的设计，可能会改成这个样子。

**Comment by hanxi** [comment]
0.3.57 发布
