### ISSUE TITLE
下载音乐事宜

### ISSUE THREAD

**Issue by zazhi4** [hanxi/xiaomusic#305]
我安装好了，第一天使用正常，能自动下载音乐。操作如下：对音箱说：播放歌曲邓丽君的小城故事，回答在下载，一会儿后就能播放（查看玩客云上music\download目录，有下载的mp3）；第2天，同样操作，让播放某某的某某，回答在下载，然后就回答播放失败。查看玩客云上music\download目录，没有下载到任何东西。
参考issue210，获取B站的cookie，通过管理平台上传，并将使用yt_dlp_cookie设为True。提交保存。不确定保存是否成功，返回object Object。请问原因？
关于下载，是否使用了youtube-dl命令行工具来下载？如果是的话，建议将MP3的比特率设到320k。我问了GPT，说在ffmpeg配合下，能设置比特率。
命令如下：youtube-dl --cookies cookies.txt -x --audio-format mp3 --audio-quality 192K https://www.bilibili.com/video/BV1xx411c7mD
供参考。

**Comment by zazhi4** [comment]
推测第2天不能用的两个原因：1，IP被封；2，不能写到预设的文件夹。关于1，不能确认，因为cookie上传可能没成功；2，可能性大些，因为不能上传，而且保存时没出现保存成功。

**Comment by hanxi** [comment]
> 不能下载，估计是我玩客云的问题。昨天重启后，能实现下载了。 希望的增强：1，前面说了，能不能功能增强为320k比特率？ 发现的问题：在预设文件夹下，music\download下，发现下载的文件，M4a，下载完以后，会生成mp3。mp3完成后，m4a就没有了，并没有转到tmp文件夹。

你发现的问题是正常的， yt-dlp 下载的时候默认转换格式后会删除旧的。比特率参数你试过有效果吗？有的话可以提个pr。

**Comment by zazhi4** [comment]
我可能没有用yt-dlp下载，因为在各个文件夹下，没看到保存的cookie。另外，是不是你已经后台设置，保存为320k啦？我下班看一下保存的MP3，用什么查一下比特率。

**Comment by hanxi** [comment]
https://stackoverflow.com/questions/49804874/download-the-best-quality-audio-file-with-youtube-dl

从这里看 --audio-quality 应该是传参数 0

**Comment by hanxi** [comment]
0.3.57 版本已经改为最高码率。
