### ISSUE TITLE
本地音频存在，它也提示当前设备没有本地歌曲，怎么解决呢?

### ISSUE THREAD

**Issue by sinojelly** [hanxi/xiaomusic#306]
2024/12/11 21:30:10  [2024-12-11 21:30:10] [0.3.48] [INFO] xiaomusic.py:1457: do_tts ok. cur_music:
2024/12/11 21:30:07  [2024-12-11 21:30:07] [0.3.48] [INFO] xiaomusic.py:1446: try do_tts value:本地没有歌曲
2024/12/11 21:30:07  [2024-12-11 21:30:07] [0.3.48] [INFO] xiaomusic.py:1354: _play_next. name:, cur_music:
2024/12/11 21:30:07  [2024-12-11 21:30:07] [0.3.48] [WARNING] xiaomusic.py:1573: 当前播放列表没有歌曲
2024/12/11 21:30:07  [2024-12-11 21:30:07] [0.3.48] [INFO] xiaomusic.py:1343: 开始播放下一首
2024/12/11 21:30:07  [2024-12-11 21:30:07] [0.3.48] [INFO] xiaomusic.py:1615: 当前歌曲  不在当前播放列表
2024/12/11 21:30:07  [2024-12-11 21:30:07] [0.3.48] [INFO] xiaomusic.py:798: 完全匹配指令. query:播放本地歌曲 opvalue:playlocal
2024/12/11 21:30:07  [2024-12-11 21:30:07] [0.3.48] [INFO] xiaomusic.py:740: 收到消息:播放本地歌曲 控制面板:False did:xxxx9

**Comment by hanxi** [comment]
播放本地歌曲+歌名

**Comment by sinojelly** [comment]
后来也没做什么操作，不知道怎么的，它好了
