### ISSUE TITLE
部分小爱音箱不能播放

### ISSUE THREAD

**Issue by sinojelly** [hanxi/xiaomusic#309]
家里有三个小爱音箱，都选中了，但是有一个小爱音箱无法播放本地歌曲。其它两个可以播。
从日志和网页界面看，它已经在播了，但是音箱没有发声。好几首本地歌曲，都是一样现象。
![image](https://github.com/user-attachments/assets/6d341363-31df-413a-af69-7bc275361b44)
日志：
2024/12/15 7:13:38  [07:13:38] [0.3.56] [INFO] 192.168.31.80:58544 - "GET /playingmusic?did=795566621 HTTP/1.1" 200
2024/12/15 7:13:35  [07:13:35] [0.3.56] [INFO] 192.168.31.80:58544 - "GET /playingmusic?did=795566621 HTTP/1.1" 200
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] ga4mp.py:224: Status code: 204
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] ga4mp.py:223: Batch Number: 1
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] ga4mp.py:183: Sending POST to: https://www.google-analytics.com/mp/collect
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1211: save_cur_config ok
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1817: 557 秒后将会播放下一首歌曲
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1895: 下一曲定时器不见了
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1889: cancel_next_timer
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] analytics.py:33: analytics run_with_cancel success
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1496: 【登鹳雀楼】已经开始播放了
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1727: group_player_play http://192.168.31.88:10090/music/%E7%99%BB%E9%B9%B3%E9%9B%80%E6%A5%BC.mp3 ['8ec1c09b-b944-41aa-a672-ae88d1106050'] [{'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}}]
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1752: play_one_url play_by_url device_id:8ec1c09b-b944-41aa-a672-ae88d1106050 ret:{'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}} url:http://192.168.31.88:10090/music/%E7%99%BB%E9%B9%B3%E9%9B%80%E6%A5%BC.mp3
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1480: 播放 http://192.168.31.88:10090/music/%E7%99%BB%E9%B9%B3%E9%9B%80%E6%A5%BC.mp3
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1869: group_force_stop_xiaoai ['8ec1c09b-b944-41aa-a672-ae88d1106050'] [None]
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1543: {'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0, 'info': '{ "status": 0, "volume": 30, "loop_type": 1 }'}}
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1532: force_stop_xiaoai player_pause device_id:8ec1c09b-b944-41aa-a672-ae88d1106050 ret:{'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}}
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1866: group_force_stop_xiaoai ['8ec1c09b-b944-41aa-a672-ae88d1106050']
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:447: 本地歌曲 登鹳雀楼 : music/登鹳雀楼.mp3 http://192.168.31.88:10090/music/%E7%99%BB%E9%B9%B3%E9%9B%80%E6%A5%BC.mp3 的时长 554 秒
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:442: get_music_sec_url. name:登鹳雀楼 filename:music/登鹳雀楼.mp3
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:397: try get_filename. filename:music/登鹳雀楼.mp3
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:428: get_music_sec_url. name:登鹳雀楼 url:http://192.168.31.88:10090/music/%E7%99%BB%E9%B9%B3%E9%9B%80%E6%A5%BC.mp3
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:507: get_music_url local music. name:登鹳雀楼, filename:登鹳雀楼.mp3
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:397: try get_filename. filename:music/登鹳雀楼.mp3
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1477: cur_music 登鹳雀楼
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1895: 下一曲定时器不见了
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1889: cancel_next_timer
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1899: cancel_group_next_timer {'795566621': <xiaomusic.xiaomusic.XiaoMusicDevice object at 0x7f67a14f0f70>}
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1348: 更新 临时搜索列表 ['登鹳雀楼', '英语八年级上五单元'] ... ['登鹳雀楼', '登鹳雀楼'] with len: 24
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:908: 根据【登鹳雀楼】找到歌曲【['登鹳雀楼']】
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:1448: playlocal. name:登鹳雀楼
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:871: 匹配到指令. opkey:播放本地歌曲 opvalue:playlocal oparg:登鹳雀楼
2024/12/15 7:13:34  [2024-12-15 07:13:34] [0.3.56] [INFO] xiaomusic.py:775: 收到消息:播放本地歌曲登鹳雀楼 控制面板:False did:795566621

**Comment by hanxi** [comment]
不能播放的是什么型号?看看设置页面勾选设备那里会有型号的。

**Comment by sinojelly** [comment]
> 不能播放的是什么型号?看看设置页面勾选设备那里会有型号的。

三个都是 LX06

**Comment by YJHUANG01** [comment]
我的也没声音，能看到音响型号为 L06A ，可以看到歌曲列表，无论是WEB端还是切换到音响播放都没有声音，连歌曲时间读条都显示00:00/00:00,MP3和无损格式都尝试过，版本：0.3.58，已尝试 打开 转换为MP3和型号兼容模式
![QQ截图20241219153850](https://github.com/user-attachments/assets/0788579a-ab16-4598-aba4-d46b14ecfe9c)
![01](https://github.com/user-attachments/assets/576b2ce9-759f-447f-927f-b2cca1f42a2e)

**Comment by hanxi** [comment]
1. 音乐格式问题，部分型号不支持 flac 。建议使用 mp3 格式的音乐文件。
2. ip 和端口配置问题，建议用测试链接播放排查。
