### ISSUE TITLE
想问下支持 LXO5 吗

### ISSUE THREAD

**Issue by Solmonz** [hanxi/xiaomusic#31]
无法运行，提示报错 没办法进去容器抓DID

**Comment by hanxi** [comment]
你可以先用这个工具试试看 https://github.com/yihong0618/MiService

**Comment by Solmonz** [comment]
已经解决了。配置好了 但是下载的歌曲他好像没办法直接播放，比如我下载了陈奕迅的十年 我喊：播放 陈奕迅十年 他还是会播放试听版本

**Comment by hanxi** [comment]
> 已经解决了。配置好了 但是下载的歌曲他好像没办法直接播放，比如我下载了陈奕迅的十年 我喊：播放 陈奕迅十年 他还是会播放试听版本

有可能是没成功登陆小米账号，或者设备类型写错了？

**Comment by Solmonz** [comment]
> > 已经解决了。配置好了 但下载的歌曲他像没办法直接播放，比如我下载了陈奕迅的十年 我喊：播放 陈奕迅十年 他还是会播放试听版本>> 有可能是没成功登陆小米账号，或者设备类型写错了？登陆了，我去问了下micli 好像是型号不支持
我用http://192.168.31.2:8090/music 1.mp4 能正常拨放

**Comment by Solmonz** [comment]
登陆了，我去问了下micli 好像是型号不支持我用http://192.168.31.2:8090/music 1.mp4 能正常拨放。<img width="666" alt="image" src="https://github.com/hanxi/xiaomusic/assets/86954956/a7f8c7a6-79d7-4003-82fa-3154d13765be">
https://github.com/yihong0618/MiService/issues/4#issuecomment-2033774453

**Comment by darkrain88** [comment]
> 已经解决了。配置好了 但是下载的歌曲他好像没办法直接播放，比如我下载了陈奕迅的十年 我喊：播放 陈奕迅十年 他还是会播放试听版本

我的也是 ， 我挂本地nas盘， 如果能有清单 点播就好了， 现在就随机播放
