### ISSUE TITLE
请问需要部署在和小爱音箱同一个局域网中吗？ 

### ISSUE THREAD

**Issue by 35763670SpadeKing** [hanxi/xiaomusic#315]
如题

**Comment by hanxi** [comment]
新手是需要的，高手可以不用。

**Comment by 35763670SpadeKing** [comment]
> 新手是需要的，高手可以不用。

什么意思？ 我在服务器上部署了，能连接上音箱下载音乐啥的，就是正常可以用了吧？

**Comment by 35763670SpadeKing** [comment]
> 新手是需要的，高手可以不用。

我在服务器上部署了，能连接上音箱下载音乐啥的，就是正常可以用了吧？

**Comment by hanxi** [comment]
是的

**Comment by zhiquanchi** [comment]
> > 新手是需要的，高手可以不用。
> 
> 我在服务器上部署了，能连接上音箱下载音乐啥的，就是正常可以用了吧？

只要填写的IP地址或这个域名小爱音响可以访问到就可以用的，我也是在服务器上部署的，在服务器上部署的，一般直接填写服务器的公网IP就可以（当然对应的端口要开放访问限制）
