### ISSUE TITLE
手动删除download目录下的文件后，不会重新下载而是播放失败

### ISSUE THREAD

**Issue by hummerstudio** [hanxi/xiaomusic#318]
因为有时候下载的歌曲不对，所以想换个关键词去下载新的歌曲，但是因为模糊匹配，会匹配到本地的，就不去下载了。
于是我手动删除download目录下的mp3文件，想着本地找不到了就会重新下载，但事情情况是似乎哪里有缓存，xiaomusic还是去本地找，然后播放的时候报播放失败。

**Comment by hanxi** [comment]
手动删除文件后，需要点一下刷新列表按钮。
