### ISSUE TITLE
升了3.60和3.61以后界面变奇怪了

### ISSUE THREAD

**Issue by drkulaasdf** [hanxi/xiaomusic#320]
升了3.60和3.61以后界面变奇怪了，播放按钮都没有了
![image](https://github.com/user-attachments/assets/bdc3fe62-e561-4bc5-8f17-8e75e3eac40e)

**Comment by hanxi** [comment]
网络问题，多刷新几次吧。

**Comment by drkulaasdf** [comment]
内外网多个设备，手机，ipad，电脑都是这样....

**Comment by hanxi** [comment]
你可以电脑按F12调试下，这是谷歌的字体文件获取不到，检查下是不是有广告拦截配错了。

**Comment by chenzhiwei** [comment]
刚才我测试了一下，google fonts有国内镜像，联通网络访问的是国内IP：

> https://fonts.googleapis.cn/css?family=Material+Icons|Material+Icons+Outlined
