### ISSUE TITLE
可以获取小爱音箱，但是不能获取本地xiaomusic/music下面的歌曲列表

### ISSUE THREAD

**Issue by nb12nb34** [hanxi/xiaomusic#326]
可以获取小爱音箱，但是不能获取本地xiaomusic/music下面的歌曲列表，在openwrt docker 下测试的

**Comment by hanxi** [comment]
检查目录挂载是否正确，检查文件是否有权限，不要修改后台设置的目录。

**Comment by nb12nb34** [comment]
找到问题了 挂载正确，web 后台目录配置需要做个设置文件目录需要做个修改，其他默认就可以了
