### ISSUE TITLE
无法播放本地音乐

### ISSUE THREAD

**Issue by fzgaoxh** [hanxi/xiaomusic#331]
播放服务器上的存放的音乐都不能正常播放了。
放上日志点播放按钮后的日志情况，大佬们可以看出是哪里问题吗
版本0.3.64

![PixPin_2024-12-25_19-22-59](https://github.com/user-attachments/assets/24f74544-8ac8-4572-96d1-0e052092455c)
![PixPin_2024-12-25_19-23-29](https://github.com/user-attachments/assets/966fd9b3-ad0f-4c79-97c0-5105fca8ba3a)
![PixPin_2024-12-25_19-16-52](https://github.com/user-attachments/assets/fff222ab-48af-4d7b-a268-093fcb7cc5c7)

**Comment by hanxi** [comment]
点网页播放按钮是否正常？F12看看网页日志是否正常。

**Comment by fzgaoxh** [comment]
点击网页播放也是不行

![PixPin_2024-12-26_20-24-39](https://github.com/user-attachments/assets/e075d3f1-447a-4c63-9b96-f5019e92b863)
![PixPin_2024-12-26_20-25-38](https://github.com/user-attachments/assets/7a66fb12-2523-4898-a229-e563aa889d4e)

**Comment by fzgaoxh** [comment]
找到问题了，配置里端口号多写了。看到这个网页播放的地址才发现问题。感谢。

**Comment by fzgaoxh** [comment]
这里一直在不停的请求，在网页中播放，这里也不停请求
还网页中播放只能播放当前选中的这一歌曲，不能播放整个列表里的歌曲。
![PixPin_2024-12-26_20-47-25](https://github.com/user-attachments/assets/d4f1be63-9408-4be0-b28c-eed2739f5661)

**Comment by hanxi** [comment]
> 这里一直在不停的请求，在网页中播放，这里也不停请求 还网页中播放只能播放当前选中的这一歌曲，不能播放整个列表里的歌曲。 ![PixPin_2024-12-26_20-47-25](https://private-user-images.githubusercontent.com/115984086/398730426-d4f1be63-9408-4be0-b28c-eed2739f5661.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMjIwNDIsIm5iZiI6MTczNTIyMTc0MiwicGF0aCI6Ii8xMTU5ODQwODYvMzk4NzMwNDI2LWQ0ZjFiZTYzLTk0MDgtNGJlMC1iMjhjLWVlZDI3MzlmNTY2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxNDAyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjVhZTQ5ZTUwOTAyYjBkZTBiMzQ2Yzc3NmIxMzA5MjY2ZDhjNmI3OWMzZjlkOGZhZDMzYjA2MTVjZmZhY2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FJ6U-HrkMs9DmgIqb3KDFanp6xkjJqbM9WWQNt931Fk)

是不是你设置成单曲循环了？
