### ISSUE TITLE
pip 安装的版本能更新一下吗

### ISSUE THREAD

**Issue by zxhans** [hanxi/xiaomusic#337]
__  __  _                   __  __                 _
 \ \/ / (_)   __ _    ___   |  \/  |  _   _   ___  (_)   ___
  \  /  | |  / _` |  / _ \  | |\/| | | | | | / __| | |  / __|
  /  \  | | | (_| | | (_) | | |  | | | |_| | \__ \ | | | (__
 /_/\_\ |_|  \__,_|  \___/  |_|  |_|  \__,_| |___/ |_|  \___|
          XiaoMusic v0.3.20 by: github.com/hanxi

还一直是0.3.20版本，能否更新到最新版，谢谢。

**Comment by hanxi** [comment]
可能是 python版本问题，升级一下python 版本试试。

**Comment by zxhans** [comment]
ok,谢谢

**Comment by zxhans** [comment]
python -V
Python 3.12.3

**Comment by hanxi** [comment]
Python 3.12.3 下载的也不行吗？

**Comment by zxhans** [comment]
是的 我现在换成docker方式了，pip的还是不会更新
