### ISSUE TITLE
下一首指令、播放歌曲指令报错

### ISSUE THREAD

**Issue by cyh1991h** [hanxi/xiaomusic#34]
[04/09/24 03:53:59] INFO     匹配到指令. opkey:下一首           xiaomusic.py:481
                             opvalue:play_next oparg:                           
                    INFO     下一首                             xiaomusic.py:515
                    WARNING  执行出错 not enough values to      xiaomusic.py:457
                             unpack (expected 2, got 1)                         
                             Traceback (most recent call last):                 
                               File                                             
                             "/app/xiaomusic/xiaomusic.py",                     
                             line 455, in run_forever                           
                                 await func(arg1=oparg)                         
                               File                                             
                             "/app/xiaomusic/xiaomusic.py",                     
                             line 523, in play_next                             
                                 await self.play(arg1=name)                     
                               File                                             
                             "/app/xiaomusic/xiaomusic.py",                     
                             line 487, in play                                  
                                 search_key,name =                              
                             kwargs["arg1"].split('|')                          
                             ValueError: not enough values to                   
                             unpack (expected 2, got 1) 

[04/09/24 03:55:08] INFO     匹配到指令. opkey:播放歌曲         xiaomusic.py:481
                             opvalue:play oparg:                                
                    WARNING  执行出错 not enough values to      xiaomusic.py:457
                             unpack (expected 2, got 1)                         
                             Traceback (most recent call last):                 
                               File                                             
                             "/app/xiaomusic/xiaomusic.py",                     
                             line 455, in run_forever                           
                                 await func(arg1=oparg)                         
                               File                                             
                             "/app/xiaomusic/xiaomusic.py",                     
                             line 487, in play                                  
                                 search_key,name =                              
                             kwargs["arg1"].split('|')                          
                             ValueError: not enough values to                   
                             unpack (expected 2, got 1)

**Comment by hanxi** [comment]
请更新最新版本试试

**Comment by hanxi** [comment]
@cyh1991h 更新后问题还存在吗？

**Comment by cyh1991h** [comment]
重新安装了，问题解决了，谢谢
