### ISSUE TITLE
windows运行install_dependencies.sh后解压报错

### ISSUE THREAD

**Issue by see-the-moment** [hanxi/xiaomusic#35]
文件一打开就损坏

**Comment by hanxi** [comment]
目前只支持linux，没在windows下运行过。具体报什么错呢？

**Comment by firstuanl** [comment]
直接下载ffmpeg安装

**Comment by hanxi** [comment]
目前应该能在 windows 下运行了，路径问题见 https://github.com/hanxi/xiaomusic/pull/107

ffmpeg 目前需要自己单独安装。
