### ISSUE TITLE
Login failed 登录报错

### ISSUE THREAD

**Issue by janewar** [hanxi/xiaomusic#38]
是群晖920上面的，有这容器项目，直接下一步配置的。
<img width="905" alt="企业微信20240429-090335@2x" src="https://github.com/hanxi/xiaomusic/assets/24662843/412064b6-fe06-4598-99ae-b63edebbaa46">
024/04/28 16:50:25	stdout	Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_iagOe6LrdZMDyqoxTCwPJGQ2X7YcF8: Login failed
2024/04/28 16:50:25	stdout	    raise Exception(f"Error {url}: {resp}")
2024/04/28 16:50:25	stdout	  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request
2024/04/28 16:50:25	stdout	    return await self.account.mi_request(
2024/04/28 16:50:25	stdout	  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 38, in mina_request
2024/04/28 16:50:25	stdout	    result = await self.mina_request("/admin/v2/device_list?master=" + str(master))
2024/04/28 16:50:25	stdout	  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 43, in device_list
2024/04/28 16:50:25	stdout	    hardware_data = await self.mina_service.device_list()
2024/04/28 16:50:25	stdout	  File "/app/xiaomusic/xiaomusic.py", line 125, in _init_data_hardware
2024/04/28 16:50:25	stdout	    await self._init_data_hardware()
2024/04/28 16:50:25	stdout	  File "/app/xiaomusic/xiaomusic.py", line 105, in init_all_data
2024/04/28 16:50:25	stdout	    await self.init_all_data(session)
2024/04/28 16:50:25	stdout	  File "/app/xiaomusic/xiaomusic.py", line 430, in run_forever
2024/04/28 16:50:25	stdout	    return future.result()
2024/04/28 16:50:25	stdout	  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2024/04/28 16:50:25	stdout	    loop.run_until_complete(xiaomusic.run_forever())
2024/04/28 16:50:25	stdout	  File "/app/xiaomusic/cli.py", line 67, in main
2024/04/28 16:50:25	stdout	    main()
2024/04/28 16:50:25	stdout	  File "/app/xiaomusic.py", line 5, in <module>
2024/04/28 16:50:25	stdout	Traceback (most recent call last):
2024/04/28 16:50:25	stdout	Exception: {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
2024/04/28 16:50:25	stdout	    raise Exception(resp)
2024/04/28 16:50:25	stdout	  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 69, in login
2024/04/28 16:50:25	stdout	Traceback (most recent call last):
2024/04/28 16:50:25	stdout	Exception on login : {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
2024/04/28 16:50:25	stdout	Exception: {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
2024/04/28 16:50:25	stdout	    raise Exception(resp)
2024/04/28 16:50:25	stdout	  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 69, in login
2024/04/28 16:50:25	stdout	Traceback (most recent call last):
2024/04/28 16:50:25	stdout	Exception on login : {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}

**Comment by janewar** [comment]
这使用说明太少了，谁写一个使用说明啊。

**Comment by hanxi** [comment]
@janewar 我没有群晖，你可以看看这篇 https://post.m.smzdm.com/p/avpe7n99/

看上去是不能使用默认的配置。

**Comment by LeanFly** [comment]
说明其实还是很清楚了。
需要根据自己的环境修改一些环境变量：

hostname 那里是你nas 的 ip
hardware 是你设备的型号
search填写搜索方式
user填写小米账号
pass填写小米账号密码

![image](https://github.com/hanxi/xiaomusic/assets/18253047/da6e4a2c-0b81-4625-a0ec-8eeb7042bb24)

这里写的相对更详尽了
https://post.smzdm.com/p/a7px7dol/

**Comment by janewar** [comment]
> @janewar 我没有群晖，你可以看看这篇 https://post.m.smzdm.com/p/avpe7n99/
> 
> 看上去是不能使用默认的配置。

的确可以启动了，控制面板可以播放。语音怎么控制。直接正常么。

**Comment by janewar** [comment]
> 说明其实还是很清楚了。 需要根据自己的环境修改一些环境变量：
> 
> hostname 那里是你nas 的 ip hardware 是你设备的型号 search填写搜索方式 user填写小米账号 pass填写小米账号密码
> 
> ![image](https://private-user-images.githubusercontent.com/18253047/326320696-da6e4a2c-0b81-4625-a0ec-8eeb7042bb24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTE2NzQsIm5iZiI6MTcxNDM5MTM3NCwicGF0aCI6Ii8xODI1MzA0Ny8zMjYzMjA2OTYtZGE2ZTRhMmMtMGI4MS00NjI1LWEwZWMtOGVlYjcwNDJiYjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExNDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZDU5MGRlY2JjNGEzYWY3YWRkMjlkMjhmNzUzYzJmMTIwOTFjYTBkNmZmY2Y1OWUyYWZlNTcxZDBhZmFiODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7Dw3ZlXUeWxxNrE0Blu_Q15bpqUNPXbFhExNyt9Dw8Q)
> 
> 这里写的相对更详尽了 https://post.smzdm.com/p/a7px7dol/

did 那个小软件不能用，
还有很早最早一代的小爱没有型号 上面有个sn那个填写什么。

**Comment by hanxi** [comment]
> File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request raise Exception(f"Error {url}: {resp}") Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_15WvxwTREVa8tCmGIUzndYlFhuZOfK: Login failed
> 
> 不知哪问题

docker 容器所在机器不能有翻墙代理。应该只要局域网的手机或者电脑重新登陆一下mi.com，让小米把你的外网ip加已验证的到白名单就行。

**Comment by hanxi** [comment]
@firstuanl 你看看这个，是不是没用桥接模式？
https://post.smzdm.com/p/a5xz5x63/

**Comment by firstuanl** [comment]
> > File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request raise Exception(f"Error {url}: {resp}") Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_15WvxwTREVa8tCmGIUzndYlFhuZOfK: Login failed
> > 不知哪问题
> 
> docker 容器所在机器不能有翻墙代理。应该只要局域网的手机或者电脑重新登陆一下 mi.com，让小米把你的外网 ip 加已验证的到白名单就行。

电脑上有翻墙就会影响到？已在电脑上mi的密码，登陆。

在yihong0618/MiService 上看到是在miaccount上直接写入用户密码才可以登陆，我是这样拿到did号。但在docker上不知怎操作。

跟这篇 [开源&Docker 篇六十二：小米/红米音箱新源，支持B站、油管音乐—xiaomusic_音箱_什么值得买]( https://post.smzdm.com/p/avpe7n99/ ) 里面评论描述一样，docker一直关闭，进不了docker操作。

我用的是ubuntu安装docker xiaomusic。

**Comment by hanxi** [comment]
@firstuanl 电脑上浏览器登陆mi的时候别翻墙，清空下浏览器cookie登陆试试。

**Comment by firstuanl** [comment]
> @firstuanl 电脑上浏览器登陆mi的时候别翻墙，清空下浏览器cookie登陆试试。

浏览器登陆很正常啊

**Comment by hanxi** [comment]
类似问题 #16
