### ISSUE TITLE
通过网页可以播放，语音怎么控制本地播放

### ISSUE THREAD

**Issue by janewar** [hanxi/xiaomusic#39]
通过网页可以播放，
但是没有播放列表
能读取本地文件夹deep文件目录生成播放列表？
语音怎么指定播放列表。

**Comment by hanxi** [comment]
不支持播放某些列表，现在是会把目录下和子目录下的文件一起随机播放。

**Comment by hanxi** [comment]
已经支持显示正在播放的歌曲和模糊搜索本地歌曲，播放列表功能还不支持。
![image](https://github.com/hanxi/xiaomusic/assets/1185757/e7581ce7-fff9-4cfa-be65-96b211b9c384)

**Comment by hanxi** [comment]
@darkrain88 本地模糊搜索具体怎么搜索不到呢？我设置了一次只给出10个结果。你方便给个示例看看你的问题吗？

```python
# 模糊搜索
def fuzzyfinder(user_input, collection):
    return difflib.get_close_matches(user_input, collection, 10, cutoff=0.1)
```

**Comment by chotamaki** [comment]
我的也是这个问题，在页面搜索可以搜索到页面也可以控制播放，但是让小爱播放的时候，它不会播放本地的音乐。比如我想听周杰伦的七里香，我说播放七里香或者周杰伦的七里香，都不能唤起本地播放。

**Comment by chotamaki** [comment]
是不是必须设置这个“XIAOMUSIC_ACTIVE_CMD 环境变量”？我没有设置这个

**Comment by hanxi** [comment]
> 是不是必须设置这个“XIAOMUSIC_ACTIVE_CMD 环境变量”？我没有设置这个

你更新试试，上一个版本有bug

**Comment by chotamaki** [comment]
> > 是不是必须设置这个“XIAOMUSIC_ACTIVE_CMD 环境变量”？我没有设置这个
> 
> 你更新试试，上一个版本有bug

不行，更新到最新版还是没法播放本地音乐

**Comment by hanxi** [comment]
> 我的也是这个问题，在页面搜索可以搜索到页面也可以控制播放，但是让小爱播放的时候，它不会播放本地的音乐。比如我想听周杰伦的七里香，我说播放七里香或者周杰伦的七里香，都不能唤起本地播放。

唤醒得说 播放歌曲 开头的。

**Comment by chotamaki** [comment]
> > 我的也是这个问题，在页面搜索可以搜索到页面也可以控制播放，但是让小爱播放的时候，它不会播放本地的音乐。比如我想听周杰伦的七里香，我说播放七里香或者周杰伦的七里香，都不能唤起本地播放。
> 
> 唤醒得说 播放歌曲 开头的。

之前我也以为是指令错了，后来发现指令对也不行。
![微信图片_20240510155901](https://github.com/hanxi/xiaomusic/assets/102281536/c62dd050-c5e4-44a4-bc63-a1934a4927bc)
这是网页搜索的结果。
![微信图片_20240510155913](https://github.com/hanxi/xiaomusic/assets/102281536/28092228-3725-4903-9fd0-c8edfab1f4d8)
这是后台的记录。
现在我发送指令 “播放歌曲夜曲”  之后，它会播报“正在下载歌曲夜曲”，然后就自己随便播放了，文件夹里也没发现下什么。
而且中午我让它停止之后，上面的光带一直在转。我的是小爱音箱pro

**Comment by hanxi** [comment]
> > > 我的也是这个问题，在页面搜索可以搜索到页面也可以控制播放，但是让小爱播放的时候，它不会播放本地的音乐。比如我想听周杰伦的七里香，我说播放七里香或者周杰伦的七里香，都不能唤起本地播放。
> > 
> > 
> > 唤醒得说 播放歌曲 开头的。
> 
> 之前我也以为是指令错了，后来发现指令对也不行。 ![微信图片_20240510155901](https://private-user-images.githubusercontent.com/102281536/329505764-c62dd050-c5e4-44a4-bc63-a1934a4927bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDA0ODYsIm5iZiI6MTcxNTM0MDE4NiwicGF0aCI6Ii8xMDIyODE1MzYvMzI5NTA1NzY0LWM2MmRkMDUwLWM1ZTQtNDRhNC1iYzYzLWExOTM0YTQ5MjdiYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMTIzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDJlY2Q1MmMwMTljZDYzNzlmMjk3ZWZiYzYwNjBmYTg3MThhMmNmYTQyMmFlZWQ5ODFmMjVjMTVkMDQxYWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-Ib72_p0rhbwa10p7tK_-U8-_2ehC7ttnn4GilseT5s) 这是网页搜索的结果。 ![微信图片_20240510155913](https://private-user-images.githubusercontent.com/102281536/329505928-28092228-3725-4903-9fd0-c8edfab1f4d8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDA0ODYsIm5iZiI6MTcxNTM0MDE4NiwicGF0aCI6Ii8xMDIyODE1MzYvMzI5NTA1OTI4LTI4MDkyMjI4LTM3MjUtNDkwMy05ZmQwLWM4ZWRmYWIxZjRkOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMTIzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmE0YjYzNjZlZmU1NTY5YjFkZmRhZmRjNDE2OTE3YjAzNjg1NjIwYjE2YzdmZTEzZTNlMGVkMWUwMmYyNWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bynykUQVEfoXcfCJ_JxpiUYwGrsqkrmejwijSMWT7fc) 这是后台的记录。 现在我发送指令 “播放歌曲夜曲” 之后，它会播报“正在下载歌曲夜曲”，然后就自己随便播放了，文件夹里也没发现下什么。 而且中午我让它停止之后，上面的光带一直在转。我的是小爱音箱pro

看看你的music目录是如何配置的

**Comment by chotamaki** [comment]
> > > > 我的也是这个问题，在页面搜索可以搜索到页面也可以控制播放，但是让小爱播放的时候，它不会播放本地的音乐。比如我想听周杰伦的七里香，我说播放七里香或者周杰伦的七里香，都不能唤起本地播放。
> > > 
> > > 
> > > 唤醒得说 播放歌曲 开头的。
> > 
> > 
> > 之前我也以为是指令错了，后来发现指令对也不行。 ![微信图片_20240510155901](https://private-user-images.githubusercontent.com/102281536/329505764-c62dd050-c5e4-44a4-bc63-a1934a4927bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDA0ODYsIm5iZiI6MTcxNTM0MDE4NiwicGF0aCI6Ii8xMDIyODE1MzYvMzI5NTA1NzY0LWM2MmRkMDUwLWM1ZTQtNDRhNC1iYzYzLWExOTM0YTQ5MjdiYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMTIzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDJlY2Q1MmMwMTljZDYzNzlmMjk3ZWZiYzYwNjBmYTg3MThhMmNmYTQyMmFlZWQ5ODFmMjVjMTVkMDQxYWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-Ib72_p0rhbwa10p7tK_-U8-_2ehC7ttnn4GilseT5s) 这是网页搜索的结果。 ![微信图片_20240510155913](https://private-user-images.githubusercontent.com/102281536/329505928-28092228-3725-4903-9fd0-c8edfab1f4d8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDA0ODYsIm5iZiI6MTcxNTM0MDE4NiwicGF0aCI6Ii8xMDIyODE1MzYvMzI5NTA1OTI4LTI4MDkyMjI4LTM3MjUtNDkwMy05ZmQwLWM4ZWRmYWIxZjRkOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMTIzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmE0YjYzNjZlZmU1NTY5YjFkZmRhZmRjNDE2OTE3YjAzNjg1NjIwYjE2YzdmZTEzZTNlMGVkMWUwMmYyNWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bynykUQVEfoXcfCJ_JxpiUYwGrsqkrmejwijSMWT7fc) 这是后台的记录。 现在我发送指令 “播放歌曲夜曲” 之后，它会播报“正在下载歌曲夜曲”，然后就自己随便播放了，文件夹里也没发现下什么。 而且中午我让它停止之后，上面的光带一直在转。我的是小爱音箱pro
> 
> 看看你的music目录是如何配置的

昨天重装了一遍，发现是“bilisearch:”后面少了个“：”导致不能从网上下载，现在好了，可以播放了，也会自己下载了，但是新问题又出现了，我映射的文件夹里有这首歌，网页端也能搜索到，但是播放的时候它又重新下载了，但是播放它自己下载过的歌曲能够直接播放，不用再下载了，难道是我放在子文件夹的原因？
![微信截图_20240511083414](https://github.com/hanxi/xiaomusic/assets/102281536/25fbf93c-26f3-4cdf-b4f5-4ab5d26cd5da)
下面那三首歌是它自己下的，实际上这些歌在子文件夹里也有。

**Comment by hanxi** [comment]
@chotamaki 子文件夹里的歌曲名字是一样的吗？必须完全一样。

**Comment by chotamaki** [comment]
> @chotamaki 子文件夹里的歌曲名字是一样的吗？必须完全一样。

肯定是一样的，搜索的时候能搜索到，但是就是无法播放本地音乐，下载之后能播放。

**Comment by hanxi** [comment]
> > @chotamaki 子文件夹里的歌曲名字是一样的吗？必须完全一样。
> 
> 肯定是一样的，搜索的时候能搜索到，但是就是无法播放本地音乐，下载之后能播放。

有可能是文件夹名字里有特殊字符没正常识别吧，我抽空测试一下。
