### ISSUE TITLE
重复下载

### ISSUE THREAD

**Issue by whyhad** [hanxi/xiaomusic#44]
本地音乐库已经有了我要播放的音乐，格式是flac，但服务仍然会去下载对应MP3格式的音乐再播放。

**Comment by whyhad** [comment]
环境是 极空间的docker

**Comment by hanxi** [comment]
是不是目录没有映射到docker里

**Comment by whyhad** [comment]
> 是不是目录没有映射到docker里

映射了，服务自己下载的音乐文件就是存放在我指定的目录里

**Comment by hanxi** [comment]
用web控制台搜索本地音乐能搜索到吗？

**Comment by hanxi** [comment]
我用语音和web控制台测试了都可以正常找到flac格式的歌曲。
![image](https://github.com/hanxi/xiaomusic/assets/1185757/9e83ed77-de96-4866-8a5a-adc3a09ad750)
你方便贴下日志看看吗？

**Comment by liuchenger** [comment]
我也遇到了，它日志里没显示搜索结果，直接下载的新的
![Uploading Screenshot_20240514_095419_com.lemurbrowser.exts_edit_289953316998661.jpg…]()

**Comment by hanxi** [comment]
> ![Screenshot_20240514_095419_com lemurbrowser exts_edit_289953316998661](https://private-user-images.githubusercontent.com/77476436/330252178-9551d4a2-abc1-4600-ab33-0d5d25d30eb8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjEzMzQsIm5iZiI6MTcxNTY2MTAzNCwicGF0aCI6Ii83NzQ3NjQzNi8zMzAyNTIxNzgtOTU1MWQ0YTItYWJjMS00NjAwLWFiMzMtMGQ1ZDI1ZDMwZWI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA0MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjNhYzhlMzA3MDZjNmRlNWJmMjk5NzEzOTI3NDQxZjFiNzRhNzFlYzVjNmMxNjhmM2QyNWYwZTk4YmU1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9EgBIvi95x8K_Yhkzo0bc1IHnJ22af59dA_FWJ0miLA) 我也遇到了，它日志里没显示搜索结果，直接下载的新的

@liuchenger 

1. 检查一下目录是否设置正确
2. 检查一下目录下是否存在 "告白气球.mp3" 或者 "告白气球.flac" 文件，文件名必须完全一致。

**Comment by liuchenger** [comment]
> > ![Screenshot_20240514_095419_com lemurbrowser exts_edit_289953316998661](https://private-user-images.githubusercontent.com/77476436/330252178-9551d4a2-abc1-4600-ab33-0d5d25d30eb8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjEzMzQsIm5iZiI6MTcxNTY2MTAzNCwicGF0aCI6Ii83NzQ3NjQzNi8zMzAyNTIxNzgtOTU1MWQ0YTItYWJjMS00NjAwLWFiMzMtMGQ1ZDI1ZDMwZWI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA0MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjNhYzhlMzA3MDZjNmRlNWJmMjk5NzEzOTI3NDQxZjFiNzRhNzFlYzVjNmMxNjhmM2QyNWYwZTk4YmU1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9EgBIvi95x8K_Yhkzo0bc1IHnJ22af59dA_FWJ0miLA) 我也遇到了，它日志里没显示搜索结果，直接下载的新的
> 
> @liuchenger
> 
> 1. 检查一下目录是否设置正确
> 2. 检查一下目录下是否存在 "告白气球.mp3" 或者 "告白气球.flac" 文件，文件名必须完全一致。

目录正确，可以下载然后播放，我原来的文件名就是告白气球.flac，然后我用文件管理器看它自己下载了一个告白气球.mp3,然后很嗨皮的播起来了，我晚上再试试其他mp3格式的歌曲是啥情况

**Comment by liuchenger** [comment]
> > ![Screenshot_20240514_095419_com lemurbrowser exts_edit_289953316998661](https://private-user-images.githubusercontent.com/77476436/330252178-9551d4a2-abc1-4600-ab33-0d5d25d30eb8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjEzMzQsIm5iZiI6MTcxNTY2MTAzNCwicGF0aCI6Ii83NzQ3NjQzNi8zMzAyNTIxNzgtOTU1MWQ0YTItYWJjMS00NjAwLWFiMzMtMGQ1ZDI1ZDMwZWI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA0MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjNhYzhlMzA3MDZjNmRlNWJmMjk5NzEzOTI3NDQxZjFiNzRhNzFlYzVjNmMxNjhmM2QyNWYwZTk4YmU1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9EgBIvi95x8K_Yhkzo0bc1IHnJ22af59dA_FWJ0miLA) 我也遇到了，它日志里没显示搜索结果，直接下载的新的
> 
> @liuchenger
> 
> 1. 检查一下目录是否设置正确
> 2. 检查一下目录下是否存在 "告白气球.mp3" 或者 "告白气球.flac" 文件，文件名必须完全一致。

测试了，目录里有告白气球.mp3，直接播；目录里有告白气球.flac，会下载告白气球.mp3，然后播放告白气球.mp3

**Comment by hanxi** [comment]
> > > ![Screenshot_20240514_095419_com lemurbrowser exts_edit_289953316998661](https://private-user-images.githubusercontent.com/77476436/330252178-9551d4a2-abc1-4600-ab33-0d5d25d30eb8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjEzMzQsIm5iZiI6MTcxNTY2MTAzNCwicGF0aCI6Ii83NzQ3NjQzNi8zMzAyNTIxNzgtOTU1MWQ0YTItYWJjMS00NjAwLWFiMzMtMGQ1ZDI1ZDMwZWI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA0MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjNhYzhlMzA3MDZjNmRlNWJmMjk5NzEzOTI3NDQxZjFiNzRhNzFlYzVjNmMxNjhmM2QyNWYwZTk4YmU1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9EgBIvi95x8K_Yhkzo0bc1IHnJ22af59dA_FWJ0miLA) 我也遇到了，它日志里没显示搜索结果，直接下载的新的
> > 
> > 
> > @liuchenger
> > 
> > 1. 检查一下目录是否设置正确
> > 2. 检查一下目录下是否存在 "告白气球.mp3" 或者 "告白气球.flac" 文件，文件名必须完全一致。
> 
> 测试了，目录里有告白气球.mp3，直接播；目录里有告白气球.flac，会下载告白气球.mp3，然后播放告白气球.mp3

帮忙看看你的 docker 镜像来自哪里的？是不是其他人打包的旧版本呢？确认一下是不是我打包的镜像 https://hub.docker.com/r/hanxi/xiaomusic

**Comment by liuchenger** [comment]
> > > > ![Screenshot_20240514_095419_com lemurbrowser exts_edit_289953316998661](https://private-user-images.githubusercontent.com/77476436/330252178-9551d4a2-abc1-4600-ab33-0d5d25d30eb8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjEzMzQsIm5iZiI6MTcxNTY2MTAzNCwicGF0aCI6Ii83NzQ3NjQzNi8zMzAyNTIxNzgtOTU1MWQ0YTItYWJjMS00NjAwLWFiMzMtMGQ1ZDI1ZDMwZWI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA0MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjNhYzhlMzA3MDZjNmRlNWJmMjk5NzEzOTI3NDQxZjFiNzRhNzFlYzVjNmMxNjhmM2QyNWYwZTk4YmU1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9EgBIvi95x8K_Yhkzo0bc1IHnJ22af59dA_FWJ0miLA) 我也遇到了，它日志里没显示搜索结果，直接下载的新的
> > > 
> > > 
> > > @liuchenger
> > > 
> > > 1. 检查一下目录是否设置正确
> > > 2. 检查一下目录下是否存在 "告白气球.mp3" 或者 "告白气球.flac" 文件，文件名必须完全一致。
> > 
> > 
> > 测试了，目录里有告白气球.mp3，直接播；目录里有告白气球.flac，会下载告白气球.mp3，然后播放告白气球.mp3
> 
> 帮忙看看你的 docker 镜像来自哪里的？是不是其他人打包的旧版本呢？确认一下是不是我打包的镜像 https://hub.docker.com/r/hanxi/xiaomusic

docker pull hanxi/xiaomusic:latest
docker pull hanxi/xiaomusic:main
都是这种情况

**Comment by hanxi** [comment]
@liuchenger 启动参数加上 --verbose 看看能不能输出  debug 级别的日志，然后帮忙看看日志里是否有告白气球.flac

**Comment by hanxi** [comment]
@liuchenger 能否截图看看你的 告白气球.flac 是不是 告白气球.FLAC ，Linux 下文件名大小写敏感的，如果是大小写的问题，可以批量改成小写。

**Comment by liuchenger** [comment]
> @liuchenger 能否截图看看你的 告白气球.flac 是不是 告白气球.FLAC ，Linux 下文件名大小写敏感的，如果是大小写的问题，可以批量改成小写。

是小写的，难道文件太大了？
![Screenshot_20240516_060853](https://github.com/hanxi/xiaomusic/assets/77476436/c99e320a-aea6-4601-9b54-8fe085a3ab76)

**Comment by hanxi** [comment]
> > @liuchenger 能否截图看看你的 告白气球.flac 是不是 告白气球.FLAC ，Linux 下文件名大小写敏感的，如果是大小写的问题，可以批量改成小写。
> 
> 是小写的，难道文件太大了？ ![Screenshot_20240516_060853](https://private-user-images.githubusercontent.com/77476436/330973953-c99e320a-aea6-4601-9b54-8fe085a3ab76.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MTMzNDgsIm5iZiI6MTcxNTgxMzA0OCwicGF0aCI6Ii83NzQ3NjQzNi8zMzA5NzM5NTMtYzk5ZTMyMGEtYWVhNi00NjAxLTliNTQtOGZlMDg1YTNhYjc2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDIyNDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MzI2ZjAyYmY2MTE5NjRhYjNlNTBmNmQ3ODYyYWFiNDg4NWMwNTA1Mjk3NGZiMjg4ZmFjMmI3ZGRjNDg0YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ob7oGGDqn_sNNbFVGGIilfyXyPasAWHlutAfHQd1c8M)

不太确定，应该跟文件大小没关系。方便开 debug 模式帮忙排查一下原因吗？

**Comment by liuchenger** [comment]
> > > @liuchenger 能否截图看看你的 告白气球.flac 是不是 告白气球.FLAC ，Linux 下文件名大小写敏感的，如果是大小写的问题，可以批量改成小写。
> > 
> > 
> > 是小写的，难道文件太大了？ ![Screenshot_20240516_060853](https://private-user-images.githubusercontent.com/77476436/330973953-c99e320a-aea6-4601-9b54-8fe085a3ab76.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MTMzNDgsIm5iZiI6MTcxNTgxMzA0OCwicGF0aCI6Ii83NzQ3NjQzNi8zMzA5NzM5NTMtYzk5ZTMyMGEtYWVhNi00NjAxLTliNTQtOGZlMDg1YTNhYjc2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDIyNDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MzI2ZjAyYmY2MTE5NjRhYjNlNTBmNmQ3ODYyYWFiNDg4NWMwNTA1Mjk3NGZiMjg4ZmFjMmI3ZGRjNDg0YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ob7oGGDqn_sNNbFVGGIilfyXyPasAWHlutAfHQd1c8M)
> 
> 不太确定，应该跟文件大小没关系。方便开 debug 模式帮忙排查一下原因吗？
更新到最新镜像，好了，没问题了
