### ISSUE TITLE
关于登陆和 播放问题

### ISSUE THREAD

**Issue by firstuanl** [hanxi/xiaomusic#48]
先感谢大佬写这么牛B的东西。

1. 用docker一直登陆不了。网上描述许多。今天用源码将用户密码写在miaccount.py,可以登陆。
2.播放音乐，（重复下载），但没有声音，谁机播放可以。那些乱码不知是什么情况。

024 11:24:31] "GET /playingmusic HTTP/1.1" 200 -
Deleting original file music/周杰伦青花瓷.m4a (pass -k to keep)
[download] Finished downloading playlist: 周杰伦青花瓷
[05/12/24 11:24:31] INFO     cur_music 周杰伦青花瓷                                                    ]8;id=709625;file:///home/firstuanl/.conda/envs/xiaomusic/xiaomusic/xiaomusic/xiaomusic.py\xiaomusic.py]8;;\:]8;id=305542;file:///home/firstuanl/.conda/envs/xiaomusic/xiaomusic/xiaomusic/xiaomusic.py#522\522]8;;\
                    INFO     播放                                                                      ]8;id=375914;file:///home/firstuanl/.conda/envs/xiaomusic/xiaomusic/xiaomusic/xiaomusic.py\xiaomusic.py]8;;\:]8;id=410104;file:///home/firstuanl/.conda/envs/xiaomusic/xiaomusic/xiaomusic/xiaomusic.py#524\524]8;;\
                             http://192.168.2.5:8090/music/%E5%91%A8%E6%9D%B0%E4%BC%A6%E9%9D%92%E8%8A%                 
                             B1%E7%93%B7.mp3                                                                           
[05/12/24 11:24:32] INFO     已经开始播放了                                                            ]8;id=446217;file:///home/firstuanl/.conda/envs/xiaomusic/xiaomusic/xiaomusic/xiaomusic.py\xiaomusic.py]8;;\:]8;id=470222;file:///home/firstuanl/.conda/envs/xiaomusic/xiaomusic/xiaomusic/xiaomusic.py#527\527]8;;\
                    INFO     歌曲 周杰伦青花瓷 : music/周杰伦青花瓷.mp3 的时长 239 秒                  ]8;id=927101;file:///home/firstuanl/.conda/envs/xiaomusic/xiaomusic/xiaomusic/xiaomusic.py\xiaomusic.py]8;;\:]8;id=242116;file:///home/firstuanl/.conda/envs/xiaomusic/xiaomusic/xiaomusic/xiaomusic.py#416\416]8;;\
                    INFO     239秒后将会播放下一首                                                     ]8;id=327755;file:///home/firstuanl/.conda/envs/xiaomusic/xiaomusic/xiaomusic/xiaomusic.py\xiaomusic.py]8;;\:]8;id=85758;file:///home/firstuanl/.conda/envs/xiaomusic/xiaomusic/xiaomusic/xiaomusic.py#430\430]8;;\
127.0.0.1 - - [12/May/2024 11:24:33] "GET /playingmusic HTTP/1.1" 200 -
127.0.0.1 - - [12/May/2024 11:24:36] "GET /playingmusic HTTP/1.1" 200 -
127.0.0.1 - - [12/May/2024 11:24:39] "GET /playingmusic HTTP/1.1" 200 -
127.0.0.1 - - [12/May/2024 11:24:42] "GET /playingmusic HTTP/1.1" 200 -
127.0.0.1 - - [12/May/2024 11:24:45] "GET /playingmusic HTTP/1.1" 200 -
127.0.0.1 - - [12/May/2024 11:24:48] "GET /playingmusic HTT

**Comment by hanxi** [comment]
XIAOMUSIC_HOSTNAME需要改成你跑这个机器的ip

**Comment by hanxi** [comment]
docker用桥接默认，不要用主机模式

**Comment by firstuanl** [comment]
好像没有重复下载了。

我是用源码，设置了XIAOMUSIC_HOSTNAME ，可以了

高级，哈哈
