### ISSUE TITLE
已经测试L05B，可以web界面控制音量，但是无法播放

### ISSUE THREAD

**Issue by wen199** [hanxi/xiaomusic#49]
在日志中显示搜索了歌曲，文件夹内也下载了歌曲，播放没有声音。
我可以配合抓包，帮助优化，但是不会写代码

**Comment by hanxi** [comment]
我试过用 [reqable](https://reqable.com/zh-CN/) 抓包安卓里的 [小爱音箱 app](https://sj.qq.com/appdetail/com.xiaomi.mico) ，能抓到播放音乐使用的是 player_play_music 接口，而不是现在代码里的 [player_play_url](https://github.com/yihong0618/MiService/blob/main/miservice/minaservice.py#L102) 接口。

你可以尝试抓包看看你的设备在小爱音箱app里是用哪个接口播放音乐，然后再尝试修改参数看看能不能播放本地音乐，也就是 xiaomusic 日志里输出的 http//xxxx:8090/music/xxx.mp3 。

**Comment by imsoso** [comment]
L06A 也一样的问题~

**Comment by mensylisir** [comment]
同，L06,播放不了

**Comment by ZYBIN-tech** [comment]
同L05B，可以web界面控制音量，但是无法播放

**Comment by lqqkk** [comment]
同，X08A，可以web界面控制音量，但是无法播放

**Comment by hanxi** [comment]
见 #30
