### ISSUE TITLE
小爱音箱app无法连接音箱，音箱显示为离线状态

### ISSUE THREAD

**Issue by liuchenger** [hanxi/xiaomusic#54]
xiaomusic连接到音箱后，发现小爱音箱app里就无法连接音箱了，音箱显示为离线状态；音箱恢复出厂设置，不运行xiaomusic，就不会有这个问题
![Screenshot_20240515_070109_com xiaomi mico](https://github.com/hanxi/xiaomusic/assets/77476436/66cb6476-7164-4c83-8f1b-b68624ce5e9a)
![Screenshot_20240515_070212_com xiaomi mico](https://github.com/hanxi/xiaomusic/assets/77476436/9131a21e-e71a-49cd-a2d4-da819fb72b75)

**Comment by hanxi** [comment]
音箱蓝牙开关打开试试？

**Comment by liuchenger** [comment]
> 音箱蓝牙开关打开试试？

蓝牙开着呢，蓝牙能连上，小爱音箱app里死活连不上，但米家app里可以连上音箱

**Comment by liuchenger** [comment]
噢，对了，MI_DID我留的空，不知道怎么看这个MI_DID，所以留的空，和这个有关系吗

**Comment by hanxi** [comment]
> 噢，对了，MI_DID我留的空，不知道怎么看这个MI_DID，所以留的空，和这个有关系吗

用这个软件查  did https://github.com/yihong0618/MiService

**Comment by liuchenger** [comment]
> > 噢，对了，MI_DID我留的空，不知道怎么看这个MI_DID，所以留的空，和这个有关系吗
> 
> 用这个软件查 did https://github.com/yihong0618/MiService

加入did之后，貌似是没问题了
