### ISSUE TITLE
播放时间是否能优化？

### ISSUE THREAD

**Issue by dzhuang** [hanxi/xiaomusic#6]
https://github.com/hanxi/xiaomusic/blob/63eb0c22cb1b95ae5128cb4bc7e68cdbf31c195b/xiaomusic/xiaomusic.py#L427-L428

在网络速度不行的情况下（比如音箱的接收wifi信号不太好时），读取音乐文件的时间会比较长，那么真正播放音乐的时间并没有达到mp3文件的长度时就结束了。

**Comment by hanxi** [comment]
有没有好的方案呢？如何在开始播放后才开始计时？

**Comment by dzhuang** [comment]
看起来现在的办法要么是把音箱放到信号好的地方，要么是减小音乐的码率。我之前下载的音乐都是高码率的，一首歌高码率音乐的在8M左右，小爱音箱从qq音乐下载的文件只有不到1.8M.

**Comment by hanxi** [comment]
播放下一首的时候判断一下是否有歌曲在播放，有就等一会。不知道效果会怎么样。

**Comment by hanxi** [comment]
暂时没有遇到更多反馈，问题估计已经解决了吧。
