### ISSUE TITLE
本地歌曲模糊搜索问题

### ISSUE THREAD

**Issue by qyxx2** [hanxi/xiaomusic#60]
请问本地的歌曲为什么搜索不到呢？我的歌曲命名方式都是类似这种"黄绮珊 希林娜依高 - 是妈妈是女儿"，跟小爱说"是妈妈是女儿"搜索不到本地的，会下载一个mp3的歌曲下来播放。网页也搜索不到。求解

**Comment by hanxi** [comment]
还没实现这个功能，过段时间会考虑实现。 web控制台支持模糊搜索，你可以先用wwb控制台试试。
https://github.com/hanxi/xiaomusic/issues/52

**Comment by hanxi** [comment]
网页端搜索的效果要看浏览器的，手机谷歌浏览器的候选列表是在输入法上面一行的，电脑浏览器就是普通的下拉列表。

**Comment by qyxx2** [comment]
谢谢可以了。用的手机edge浏览器没有显示，输入法上面只有小圆圈。换成谷歌浏览器就可以显示了。希望可以适配小爱模糊搜索本地的功能~
