### ISSUE TITLE
XIAOMUSIC_PROXY 怎么填   从油管下载音乐下不下来

### ISSUE THREAD

**Issue by hbhqqq** [hanxi/xiaomusic#63]
成功运行。下载音乐下载不了 播放音乐还是提示开会员

**Comment by hanxi** [comment]
- XIAOMUSIC_SEARCH: 'ytsearch:'
- XIAOMUSIC_PROXY: 'http://192.168.2.5:8080'

XIAOMUSIC_PROXY 是你翻墙的 http 代理地址，一般的翻墙软件都会有是否允许局域网访问，允许局域网访问就会显示地址和端口的。

你的应该是其他配置还没配对，配对了会有拦截语音提示，比如正在下载中这样的提示。

**Comment by hanxi** [comment]
关键问题 #2 #11
