### ISSUE TITLE
播放期间设置的音量

### ISSUE THREAD

**Issue by dzhuang** [hanxi/xiaomusic#7]
在播放其中一首歌时设置的音量，使用"下一首"指令后，音量会重置到设置前的水平。

**Comment by hanxi** [comment]
我重现了，但是找不到原因所在。

**Comment by hanxi** [comment]
不知道最新版本解决了没？估计是命令模式和api模式的区别，目前把默认默认改成api模式了。

**Comment by liuchenger** [comment]
播放期间，喊小爱同学调音箱音量后，音乐就暂停不放了

**Comment by hanxi** [comment]
> 播放期间，喊小爱同学调音箱音量后，音乐就暂停不放了

目前是这样的，可以考虑优化一下这个。

**Comment by hanxi** [comment]
目前可以使用控制台设置声音，应该修复了这个问题。
