### ISSUE TITLE
随机播放和循环播放出现的问题

### ISSUE THREAD

**Issue by jock101** [hanxi/xiaomusic#70]
用口令播放歌曲成功下载播放后，觉得不好听，在文件夹将歌曲删除后，下次还会自动下载播放，除非重启容器，希望删除后就忽略了。

**Comment by hanxi** [comment]
好的

**Comment by hanxi** [comment]
@jock101 有空帮忙测试一下，docker 需要更新 main 版本镜像测试。

`docker pull hanxi/xiaomusic:main`

**Comment by jock101** [comment]
@hanxi 重复下载的问题没有了，但会提示本地没有歌曲，然后就不播放了。

**Comment by hanxi** [comment]
> @hanxi 重复下载的问题没有了，但会提示本地没有歌曲，然后就不播放了。

等我复现一下看看

**Comment by hanxi** [comment]
> @hanxi 重复下载的问题没有了，但会提示本地没有歌曲，然后就不播放了。

请问复现步骤是什么呢？我没有复现出来，你是把目录里的歌曲全清空了吗？

**Comment by jock101** [comment]
> 请问复现步骤是什么呢？我没有复现出来，你是把目录里的歌曲全清空了吗？

我测试的是0.37的main版本，我把大部分歌曲移到别的文件夹了，留了两首，然后用口令下载播放一首，然后删除它。

**Comment by hanxi** [comment]
> > 请问复现步骤是什么呢？我没有复现出来，你是把目录里的歌曲全清空了吗？
> 
> 我测试的是0.37的main版本，我把大部分歌曲移到别的文件夹了，留了两首，然后用口令下载播放一首，然后删除它。

有空再用新版本试试看？我昨晚也是这样测试的，可能新增播放列表功能的时候顺带修复了。

**Comment by jock101** [comment]
> > > 请问复现步骤是什么呢？我没有复现出来，你是把目录里的歌曲全清空了吗？
> > 
> > 
> > 我测试的是0.37的main版本，我把大部分歌曲移到别的文件夹了，留了两首，然后用口令下载播放一首，然后删除它。
> 
> 有空再用新版本试试看？我昨晚也是这样测试的，可能新增播放列表功能的时候顺带修复了。

好的，晚上回去再试试。谢谢。

**Comment by jock101** [comment]
> > > 请问复现步骤是什么呢？我没有复现出来，你是把目录里的歌曲全清空了吗？
> > 
> > 
> > 我测试的是0.37的main版本，我把大部分歌曲移到别的文件夹了，留了两首，然后用口令下载播放一首，然后删除它。
> 
> 有空再用新版本试试看？我昨晚也是这样测试的，可能新增播放列表功能的时候顺带修复了。

新版没有这个问题了，一切正常。
