### ISSUE TITLE
是不是可以xiaomusic最后也还是走歌单的模式

### ISSUE THREAD

**Issue by 739342280** [hanxi/xiaomusic#72]
类似网易云，播放以歌单为模式（当然也可以播放全部歌曲）。
另，请问作者是否有意把gui美化一下，考不考虑图片？，最简单的比如windows的图片这种
![QQ截图20240615233503](https://github.com/hanxi/xiaomusic/assets/104440579/05e1bf9d-648d-44b8-8863-e7f19439bb16)

**Comment by hanxi** [comment]
歌单模式有个优点就是不用下载歌曲，保留建议，暂时不会接入。

gui 我不太会搞，希望有人来帮忙搞一搞。

**Comment by 739342280** [comment]
收到，谢谢

**Comment by 739342280** [comment]
> 歌单模式有个优点就是不用下载歌曲，保留建议，暂时不会接入。
> 
> gui 我不太会搞，希望有人来帮忙搞一搞。

感谢回复，谢谢
