### ISSUE TITLE
ubus接口格式错误

### ISSUE THREAD

**Issue by A-Cepheus** [hanxi/xiaomusic#73]
docker部署，提示`Exception: Error https://api2.mina.mi.com/remote/ubus: {"code":601,"message":"illegal argument exception","data":"IllegalArgumentException: ubus call format illegal!"}`

**Comment by hanxi** [comment]
有没有完整的日志？

**Comment by hanxi** [comment]
也说下是什么应该

**Comment by hanxi** [comment]
#74 这里优化了这个问题，可以配置独立的配置目录，需要重新保存一下设置。

**Comment by losingrose** [comment]
MI_HARDWARE='X08E'

**Comment by losingrose** [comment]
还有ipv6的绑定是host = "::"，建议吧host = "0.0.0.0"参数也写成环境变量。

**Comment by hanxi** [comment]
> 还有ipv6的绑定是host = "::"，建议吧host = "0.0.0.0"参数也写成环境变量。

不想ipv6被访问到端口可以在docker配端口时修改的，见 https://stackoverflow.com/questions/30750271/disable-ip-v6-in-docker-container

也可以配防火墙禁用就行了的。
