### ISSUE TITLE
大佬我用群晖docker 启动安装的，但他只能播放docker 文件夹的内容，本地播放表加入后，后台显示播放，但音箱无反应。

### ISSUE THREAD

**Issue by jack2365** [hanxi/xiaomusic#75]
只能播放自己在docker 新建的文件夹，改成nas 存的音乐就播放没有声音了，还特地选择了mp3格式。看日志咋选者了本地文件夹，还去走代理去搜索，有点不能理解：
<img width="895" alt="截屏2024-06-22 05 30 47" src="https://github.com/hanxi/xiaomusic/assets/60833931/e637d906-f5d7-4d4d-becf-167c640f8ecf">
<img width="1098" alt="截屏2024-06-22 05 31 01" src="https://github.com/hanxi/xiaomusic/assets/60833931/de8cde24-cf4e-4b9b-8b1d-f543aeb46a45">
<img width="553" alt="截屏2024-06-22 05 32 01" src="https://github.com/hanxi/xiaomusic/assets/60833931/0b2bc399-7d06-4d08-9a22-3aec497a4701">
[hanxi-xiaomusic.html.zip](https://github.com/user-attachments/files/15933941/hanxi-xiaomusic.html.zip)

查看日志经常抱这个错：
[21:14:37] [0.1.52] [WARNING] 执行出错 Error https://api2.mina.mi.com/remote/ubus: {"code":601,"message":"illegal argument exception","data":"IllegalArgumentException: ubus call format illegal!"}

**Comment by hanxi** [comment]
从截图看你配的目录是不是没挂载进docker里。可以重启或者刷新列表看看是否生效。

**Comment by hanxi** [comment]
音箱型号说一下。

**Comment by jack2365** [comment]
这是改回来了，正常播放的文件夹 型号：小米音箱第二代 机身上没有型号
![3719DB13-9A38-4681-B8F4-F589A7339FD1](https://github.com/hanxi/xiaomusic/assets/60833931/35181602-4ad3-4f9e-9fb3-d6a6194dc82a)
这是群晖音乐文件夹，网页端可以看到音乐列表，可以选择播放，就是音箱没有声音！
![A1251CEF-E582-4DCD-96A5-75039D5731BD](https://github.com/hanxi/xiaomusic/assets/60833931/d32b371e-2049-4ef1-af2c-5d1c4741870b)
![76C9A2D5-B11C-4AB4-98F8-0DDEDF73BBFF](https://github.com/hanxi/xiaomusic/assets/60833931/03a6e2ce-9926-4520-954b-a841b4e06f66)

**Comment by hanxi** [comment]
![image](https://github.com/hanxi/xiaomusic/assets/1185757/f194ba99-37c0-4c8b-896e-257872475c89)
@jack2365 目录挂载对的吗？

**Comment by jack2365** [comment]
目前挂在的是自建的docker 文件夹 没有用本地音乐文件夹了

**Comment by jack2365** [comment]
感谢大佬的解答 我先用着吧
