### ISSUE TITLE
生成播放列表能不能勾选只选择根目录下文件夹，生成太多了

### ISSUE THREAD

**Issue by lfx285** [hanxi/xiaomusic#76]
生成播放列表能不能勾选只选择根目录下文件夹，生成太多了好乱

**Comment by hanxi** [comment]
可以考虑加个配置目录层级

**Comment by jock101** [comment]
> 可以考虑加个配置目录层级

另外建议一下能不能后台自动刷新列表（不暂停播放）或者点击刷新列表时后台执行，不暂停播放。暂停播放挺影响体验的。

**Comment by hanxi** [comment]
现在刷新列表会暂停播放？好像随机播放按钮那些会打断播放，我想想有没有不打断播放的办法。

**Comment by jock101** [comment]
> 现在刷新列表会暂停播放？好像随机播放按钮那些会打断播放，我想想有没有不打断播放的办法。

在操控面板点刷新列表，会语音提示刷新成功，然后就不放了。

**Comment by hanxi** [comment]
> > 现在刷新列表会暂停播放？好像随机播放按钮那些会打断播放，我想想有没有不打断播放的办法。
> 
> 在操控面板点刷新列表，会语音提示刷新成功，然后就不放了。

好的，谢谢反馈，我会今早优化一下。
