### ISSUE TITLE
XIAOMUSIC_ACTIVE_CMD  这个需要怎么配置，没看明白

### ISSUE THREAD

**Issue by binghan2000** [hanxi/xiaomusic#79]
XIAOMUSIC_ACTIVE_CMD  这个需要怎么配置，没看明白

**Comment by hanxi** [comment]
你可以看看这个 https://github.com/hanxi/xiaomusic/pull/43

**Comment by hanxi** [comment]
默认情况下就满足了，你可以不用配置的。

**Comment by baiqianlover** [comment]
> XIAOMUSIC_ACTIVE_CMD 这个需要怎么配置，没看明白

就是环境变量   -e   底下加上
