### ISSUE TITLE
能否添加继续播放这个功能

### ISSUE THREAD

**Issue by u2gign** [hanxi/xiaomusic#81]
因为平时听评书相声比较多，停止播放后，往往再次播放需要手动到页面去进行选择，能否添加功能“继续播放”能够在上次暂停的位置继续进行播放，感谢开发者

**Comment by hanxi** [comment]
目前抓到的接口做不到从中间继续播放，只能重新开始播放单个文件，你可以考虑把文件切分的更细一点缓解这个问题。

**Comment by darkrain88** [comment]
要求越来越过分， 哈哈

**Comment by u2gign** [comment]
哈哈 因为每次播放列表，都不可控制它的播放顺序，这个确认有些抓狂

**Comment by hanxi** [comment]
> 哈哈 因为每次播放列表，都不可控制它的播放顺序，这个确认有些抓狂

现在应该是支持顺序播放了，文件名前面或者后面加个数字，会按数字大小排序。

**Comment by u2gign** [comment]
非常感谢

**Comment by hanxi** [comment]
> > 目前抓到的接口做不到从中间继续播放，只能重新开始播放单个文件，你可以考虑把文件切分的更细一点缓解这个问题。
> 
> 我觉得题主的意思应该是暂停后可以继续播放上个音频，只要是这个音频就可以了，不需要从中间继续播放。目前应该每次重新开始都是从列表的第一个音频开始放。

目前点击关机后再点击播放应该是会继续播放的吧？

**Comment by u2gign** [comment]
> > > 目前抓到的接口做不到从中间继续播放，只能重新开始播放单个文件，你可以考虑把文件切分的更细一点缓解这个问题。
> > 
> > 
> > 我觉得题主的意思应该是暂停后可以继续播放上个音频，只要是这个音频就可以了，不需要从中间继续播放。目前应该每次重新开始都是从列表的第一个音频开始放。
> 
> 目前点击关机后再点击播放应该是会继续播放的吧？

目前是直接喊小爱 来播放音频列表，感觉每次开始的播放位置都不太相同呢，不知道跟刷新列表有无关系，今天回家我再试试
