### ISSUE TITLE
XIAOMUSIC_HOSTNAME支持ipv6吗

### ISSUE THREAD

**Issue by u2gign** [hanxi/xiaomusic#84]
是否支持域名

**Comment by hanxi** [comment]
你可以试试看，有人直接配局域网的ipv4，外网也能用ipv6访问的。XIAOMUSIC_HOSTNAME 主要是为了给局域网的小爱音箱访问局域网的音乐的，web后台地址跟这个无关。

**Comment by u2gign** [comment]
好的 我试试看

**Comment by 739342280** [comment]
如果有软路由的话，可以使用端口转发，这样你能做到v6访问。

**Comment by hanxi** [comment]
已经有人测试过小爱音箱不支持ipv6的歌曲地址，所以只能做到ipv6访问web地址操作而已，给音乐播放的mp3音乐地址还是需要ipv4。
