### ISSUE TITLE
播放功能及播放歌单建议

### ISSUE THREAD

**Issue by newrookie001** [hanxi/xiaomusic#85]
L06A，目前已经能够正常使用播放功能，有几个建议：
1、希望能够接受模糊指令。
目前只能<“播放歌曲”+"丢手绢">格式进行点歌，但看看能否做到模糊指令<“播放”+“丢手绢”>；若担心误触发系统自带指令调用，web可以添加一个开关，用户自己选择是否完全关闭系统内置音乐调用。

2、除了本地已下载歌曲，目前不支持网络点歌连续播放。
比如，“播放歌曲 周*伦的歌”，后台会从b站调用资源进行播放，但播完一首后不会自动播放“周*伦”其他歌曲，而是开始自动调用本地前期已下载的进行播放（不是周*伦的），而是前期所有点播过的历史记录。希望能实现网络点歌后，能够一直按照指令内容顺序播放下去。

3、歌单方面，目前需要m3u格式且转换成json，但酷某、网亿云的音乐歌单都是这个样式，并不是m3u：
https://www.kuwo.cn/playlist_detail/3135508477
https://music.163.com/#/playlist?id=610040691
那用户在web侧，只需要粘贴上面网址就行，后台只要读取歌单里面具体的“歌名+歌手”，然后自动检索Bili、YouT相关资源进行播放即可，实际上需要的只是歌单的内容，资源调用并不一定在原播放器。同时，可以对歌单进行自主命名。
同样，电台也可以找一些类似网址接口复制进去。

4、在歌单的基础上，增加定时播放、定时关闭，特定歌单的功能。

5、考虑到这个应用的普适性，适配天猫、百度等音响，可以考虑用Dlna，这样能够减少适配上的工作。
可以参考：
https://github.com/UniversalMediaServer/UniversalMediaServer
https://github.com/gerbera/gerbera?tab=readme-ov-file

**Comment by hanxi** [comment]
1. 模糊匹配功能在计划中了，见 https://github.com/hanxi/xiaomusic/issues/52
2. 有个批量下载歌单里的需求还在计划中但是搁置了，后面再想想怎么实现，可以考虑实现。 https://github.com/hanxi/xiaomusic/issues/51
3. 看了下这2个歌单都不能直接获取到播放链接，都有防爬虫处理，可以通过制作类似m3u那个转换工具获取播放链接，放到未来计划中，如果其他人有兴趣能搞一下。
4. 已经支持定时关闭，定时播放可以考虑。
5. dlna 功能也有其他人提到过，暂时待定。

**Comment by hanxi** [comment]
https://github.com/hanxi/xiaomusic/issues/212

**Comment by hanxi** [comment]
https://github.com/hanxi/xiaomusic/issues/182

**Comment by hanxi** [comment]
3和5暂时不打算搞了。
