### ISSUE TITLE
建议增加一个收藏功能

### ISSUE THREAD

**Issue by lfx285** [hanxi/xiaomusic#87]
现在的播放列表还是局限了，我的音乐按照歌手文件夹形式储存，所以基本只能限定播放列表播谁的歌，要不然就随机播放全部。ps：我不想搞乱本地的储存结构。
建议增加一个收藏本地歌曲条目的功能，相当于一个列表，里面是收藏后的歌曲完整路径。
这样就能做到播放收藏歌曲，也就是经常听的，还可以自由编辑列表而不改变储存目录结构
语音：播放收藏列表，播放收藏，播放我喜欢的，播放我的收藏；收藏（添加播放歌曲到收藏列表），取消收藏（删除播放歌曲到收藏列表）。

**Comment by hanxi** [comment]
这个建议不错，目前支持网络歌单后，可以比较方便就能实现这个功能。

**Comment by 739342280** [comment]
其实可以增加一个“收藏”的播放列表，然后增加一个收藏本歌曲的按键功能，点按之后，歌曲从目前的文件夹拷贝一份到收藏文件夹

**Comment by lfx285** [comment]
> 其实可以增加一个“收藏”的播放列表，然后增加一个收藏本歌曲的按键功能，点按之后，歌曲从目前的文件夹拷贝一份到收藏文件夹

这样确实从程序上更简单了，不过对于大型音乐库会很占空间，并且会造成重复歌曲，如果你有其他刮削程序会更难管理音乐库

**Comment by hanxi** [comment]
用网络歌单的模式实现也还算简单，维护一个收藏列表，保存为json格式，也存到setting.json里。json里只有名字和url，也可以用上type字段标记是本地的还是网络的。

**Comment by hanxi** [comment]
新版本已经支持。

**Comment by lfx285** [comment]
> 新版本已经支持。

牛啊
