### ISSUE TITLE
选的是bilisearch，为什么下载的都是m4a格式，不能播放

### ISSUE THREAD

**Issue by puexine** [hanxi/xiaomusic#89]

**Comment by hanxi** [comment]
你的设备的cpu是不是armv7的，目前包里的ffmpeg只支持arm64和amd64的，所以会转格式失败。可以参考这个回复，自己安装 ffmpeg 试试，后期考虑优化 armv7 的包。

https://github.com/hanxi/xiaomusic/issues/30#issuecomment-2187820999

**Comment by puexine** [comment]
确实是v7，好的，感谢大佬！

**Comment by hanxi** [comment]
已经支持 armv7，本地已经支持m4a，但是mp3格式更通用，目前还是采用下载mp3格式文件。

**Comment by wjcroom** [comment]
> 已经支持 armv7，本地已经支持m4a，但是mp3格式更通用，目前还是采用下载mp3格式文件。

似乎flac,wav都可以吧,林外我在研究  空痕的下载器,后台是php的接口, 支持导入歌单. 也可单文件. 可选3类音质.   可选音源,  是不是比biliserarch强大些呢?

**Comment by hanxi** [comment]
> > 已经支持 armv7，本地已经支持m4a，但是mp3格式更通用，目前还是采用下载mp3格式文件。
> 
> 似乎flac,wav都可以吧,林外我在研究 空痕的下载器,后台是php的接口, 支持导入歌单. 也可单文件. 可选3类音质. 可选音源, 是不是比biliserarch强大些呢?

可以写插件支持的，参考其他音源插件吧。

**Comment by wjcroom** [comment]
> > > 已经支持 armv7，本地已经支持m4a，但是mp3格式更通用，目前还是采用下载mp3格式文件。
> > 
> > 
> > 似乎flac,wav都可以吧,林外我在研究 空痕的下载器,后台是php的接口, 支持导入歌单. 也可单文件. 可选3类音质. 可选音源, 是不是比biliserarch强大些呢?
> 
> 可以写插件支持的，参考其他音源插件吧。

依托他的api，随时停用。而且，还会侵权。  我搜到一个网易的命令行开源的，大概可以这样。 绑定上会员，人家在小爱官方就有了。。。

暂停再观察。我只是发现，空痕下载歌单真是狠
