### ISSUE TITLE
能否记忆播放列表；加上上一首功能；环境变量过多

### ISSUE THREAD

**Issue by 739342280** [hanxi/xiaomusic#90]
作者你好。

- [x] 1.请问能否重启或关闭后再打开时**保留上次的播放列表而不是变成播放列表变成“全部”**
理由：这样钟情于一个歌单的时候不用因为更新或关机重启而再进行额外的操作。
- [x] 2.现在已经有下一首的网页和语音功能，请问能否考虑增加上一首的功能。
理由：这样想再听一遍上一首的时候可以方便聆听。
- [x] 3.目前可定义的环境变量已经很多了（大于十个），请问能否考虑逐渐将环境变量逐渐迁移到网页上配置。
理由：这样方便配置及查看，也便于新手操作。

**Comment by hanxi** [comment]
可以的。

**Comment by hanxi** [comment]
第3点已经实现，1，2点后期会考虑实现。

**Comment by hanxi** [comment]
下个版本发布会有这些功能。
