### ISSUE TITLE
增加搜索本地歌曲播放功能？

### ISSUE THREAD

**Issue by wangweitung** [hanxi/xiaomusic#92]
因为本地收藏了很多儿歌，小朋友想听其中某一首。

能否在面板里增加搜索本地歌曲+播放功能？

**Comment by jock101** [comment]
一直就能搜索啊，在第一个框里输入就行，支持模糊搜索。

**Comment by lfx285** [comment]
本地播放搜索最好是自己把歌曲文件名整理好，模糊搜索现在默认60%匹配才能确认，如果无关字符太多会导致搜不到

**Comment by wangweitung** [comment]
![IMG_20240630_122751](https://github.com/hanxi/xiaomusic/assets/8080125/554c6aa6-13d7-43f3-bcc6-4776fd5598d5)
目录里有逃跑计划
搜索后，没有播放本地，而是重新下载了。

**Comment by hanxi** [comment]
> ![IMG_20240630_122751](https://private-user-images.githubusercontent.com/8080125/344443318-554c6aa6-13d7-43f3-bcc6-4776fd5598d5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MjIwMjYsIm5iZiI6MTcxOTcyMTcyNiwicGF0aCI6Ii84MDgwMTI1LzM0NDQ0MzMxOC01NTRjNmFhNi0xM2Q3LTQzZjMtYmNjNi00Nzc2ZmQ1NTk4ZDUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMDQyODQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDYzNmQyMTA3ZWEwYTNmMDA2NTA3NGU5ZDU4NWI3ZmY5Yzc3NjBjMGYyZmI4YzYyNDRlZDI5N2U2MTVjN2EzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4PW6p5vERSCuYkbb27D3p2rpSZgH0UQ7gbPDRF6O8ZY) 目录里有逃跑计划 搜索后，没有播放本地，而是重新下载了。

输入逃跑计划时，应该会出现候选列表的，你换个浏览器试试？

**Comment by wangweitung** [comment]
是否可以加个搜索，后面加个播放。而不是只能搜索播放合并了。

![IMG_20240630_123211](https://github.com/hanxi/xiaomusic/assets/8080125/e85069f3-bcfe-4d60-b973-e97f4501e925)

**Comment by hanxi** [comment]
候选列表匹配是用的10%的匹配度，直接播放的匹配度默认是 60%，这个有配置可以改。

**Comment by hanxi** [comment]
@wangweitung 手机浏览器的搜索候选列表一般在输入法上面，你看看你的有没有。

**Comment by hanxi** [comment]
> 是否可以加个搜索，后面加个播放。而不是只能搜索播放合并了。
> 
> ![IMG_20240630_123211](https://private-user-images.githubusercontent.com/8080125/344443422-e85069f3-bcfe-4d60-b973-e97f4501e925.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MjIyOTcsIm5iZiI6MTcxOTcyMTk5NywicGF0aCI6Ii84MDgwMTI1LzM0NDQ0MzQyMi1lODUwNjlmMy1iY2ZlLTRkNjAtYjk3My1lOTdmNDUwMWU5MjUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMDQzMzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM2Y2FkNjM4YjlhZjIzM2MxNmE4ZGMwZDc2YzFlNDdkZmY4ZGVmNWU2MDk0NmU3ZDU4YjJlOWEyMjRhODliOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3-CTpD-bB6RRPvAiWVyhdKV_e8AoxlGN8A4-OczkSlQ)

等新版本的ui吧，估计会做成和音乐播放器那种搜索界面一样。

**Comment by wangweitung** [comment]
> @wangweitung 手机浏览器的搜索候选列表一般在输入法上面，你看看你的有没有。

有弹出选项：
 - web端 Chrome 。
 - 手机端Chrome
 - iPad Safari 

无弹出：
 - 手机端Firfox无弹出。

**Comment by hanxi** [comment]
感谢反馈，后续会考虑优化候选列表展示效果。

**Comment by hanxi** [comment]
新UI会重新设计搜索界面。
