### ISSUE TITLE
能否将一级目录作为播放列表？

### ISSUE THREAD

**Issue by wangweitung** [hanxi/xiaomusic#93]
当前逻辑是：所有的文件夹都作为播放列表：
【周杰伦】
 - 【专辑1】
 - 【专辑2】
 - 【专辑3】

可我只需要将【周杰伦】文件夹作为播放列表。

能否增加此功能优化？谢谢~

**Comment by lfx285** [comment]
已经有了深度设置了，不过二级目录的歌曲仍然获取不到，好像设置深度后列表和检索歌曲都只按照设置的深度检索，感觉还能优化一下

**Comment by hanxi** [comment]
> 已经有了深度设置了，不过二级目录的歌曲仍然获取不到，好像设置深度后列表和检索歌曲都只按照设置的深度检索，感觉还能优化一下

确实没考虑到这个问题，检索深度和生成播放列表要分开搞。

**Comment by hanxi** [comment]
确认一下是不是这样的效果，比如深度设为2，目录机构如下:
```
a                                                       
a/b3.txt                                                
a/b1.txt                                                
a/b                                                     
a/b/c2.txt                                              
a/b/c1.txt                                              
a/b/c                                                   
a/b/c/d                                                 
a/b/c/d/e2.txt                                          
a/b/c/d/e1.txt                                          
a/b/c/d/e                                               
a/b/c/d/e/f2.txt                                        
a/b/c/d/e/f1.txt                                        
a/b/c/d/e/f
a/b/c/d/e/f/g1.txt                                      
a/b/c/d/e/f/g2.txt
a/b/c/d1.txt
a/b/c/d2.txt                                            
a/b/c/d3.txt
a/b/c3.txt                                              
a/b2.txt
```

搜索出的结果如下: 只有 a 和 a/b 两层，大于2的都集中到 第二层里。
```
a: ['a/b3.txt', 'a/b1.txt', 'a/b2.txt']                 

a/b: ['a/b/c2.txt', 'a/b/c1.txt', 'a/b/c3.txt', 'a/b/c/d1.txt', 'a/b/c/d2.txt', 'a/b/c/d3.txt', 'a/b/c/d/e2.txt', 'a/b/c/d/e1.txt', 'a/b/c/d/e/f2.txt', 'a/b/c/d/e/f1.txt', 'a/b/c/d/e/f/g1.txt', 'a/b/c/d/e/f/g2.txt']

```

**Comment by hanxi** [comment]
关联需求 https://github.com/hanxi/xiaomusic/issues/76

**Comment by lfx285** [comment]
> 确认一下是不是这样的效果，比如深度设为2，目录机构如下:
> 
> ```
> a                                                       
> a/b3.txt                                                
> a/b1.txt                                                
> a/b                                                     
> a/b/c2.txt                                              
> a/b/c1.txt                                              
> a/b/c                                                   
> a/b/c/d                                                 
> a/b/c/d/e2.txt                                          
> a/b/c/d/e1.txt                                          
> a/b/c/d/e                                               
> a/b/c/d/e/f2.txt                                        
> a/b/c/d/e/f1.txt                                        
> a/b/c/d/e/f
> a/b/c/d/e/f/g1.txt                                      
> a/b/c/d/e/f/g2.txt
> a/b/c/d1.txt
> a/b/c/d2.txt                                            
> a/b/c/d3.txt
> a/b/c3.txt                                              
> a/b2.txt
> ```
> 
> 搜索出的结果如下: 只有 a 和 a/b 两层，大于2的都集中到 第二层里。
> 
> ```
> a: ['a/b3.txt', 'a/b1.txt', 'a/b2.txt']                 
> 
> a/b: ['a/b/c2.txt', 'a/b/c1.txt', 'a/b/c3.txt', 'a/b/c/d1.txt', 'a/b/c/d2.txt', 'a/b/c/d3.txt', 'a/b/c/d/e2.txt', 'a/b/c/d/e1.txt', 'a/b/c/d/e/f2.txt', 'a/b/c/d/e/f1.txt', 'a/b/c/d/e/f/g1.txt', 'a/b/c/d/e/f/g2.txt']
> ```

这样非常合理

**Comment by hanxi** [comment]
@wangweitung 有空可以帮忙测试一下是否正常，你可以设置深度为2试试。

**Comment by wangweitung** [comment]
> @wangweitung 有空可以帮忙测试一下是否正常，你可以设置深度为2试试。

好的，我是docker部署，等镜像更新测试后反馈。

**Comment by hanxi** [comment]
https://github.com/hanxi/xiaomusic/releases/tag/v0.1.98 新版本已出。

**Comment by wangweitung** [comment]
> https://github.com/hanxi/xiaomusic/releases/tag/v0.1.98 新版本已出。

已OK，感谢开发者~👍
