### ISSUE TITLE
下载的目录与本地音乐目录分开

### ISSUE THREAD

**Issue by redjumper** [hanxi/xiaomusic#98]
建议将下载的目录与本地音乐目录分开。比如本地音乐目录/music，下载的目录在一个独立的文件夹中，如本地音乐目录下的子目录/music/download

**Comment by hanxi** [comment]
新增 XIAOMUSIC_DOWNLOAD_PATH 变量可以配置下载目录，默认为空，表示使用 music 目录为下载目录。设置这个目录必须是 music 的子目录，否则刷新列表后会找不到歌曲。

**Comment by hanxi** [comment]
会在 v0.1.93 版本生效，也可以在测试版本中测试使用。
